(()=>{
const $=id=>document.getElementById(id), qs=s=>document.querySelectorAll(s);
const ids=['sensitivity','mouthEx','smoothing','roundness','blinkRate','headMotion','eyeMotion','headWidth','headLength','eyeSpacing','eyeSize','mouthWidth','browHeight'];
const c=Object.fromEntries(ids.map(id=>[id,$(id)]));
const defaults=Object.fromEntries(ids.map(id=>[id,c[id].value]));
const svg={headGroup:$('headGroup'),head:$('head'),glow:$('headGlow'),hair:$('hair'),earL:$('earL'),earR:$('earR'),eyeL:$('eyeLineL'),eyeR:$('eyeLineR'),irisL:$('irisL'),irisR:$('irisR'),lidL:$('lidL'),lidR:$('lidR'),browL:$('browL'),browR:$('browR'),mouth:$('mouth'),teeth:$('teeth'),chin:$('chin')};
let ac,analyser,stream,source,mic=false,demo=false,level=0,smooth=0,centroid=.5,last=performance.now(),nextBlink=last+1800,blink=0,blinkDir=0,nextEye=0,eyeX=0,eyeY=0,targetX=0,targetY=0;
const td=new Uint8Array(2048), fd=new Uint8Array(1024);
function outputs(){ids.forEach(id=>{const o=$(id+'Out'); if(o)o.textContent=id==='browHeight'?`${Math.round(+c[id].value)}px`:(+c[id].value).toFixed(2).replace(/\.00$/,'')});}
function notice(t,ok=false){const n=$('notice'); n.textContent=t;n.hidden=false;n.classList.toggle('ok',ok);setTimeout(()=>{if(n.textContent===t)n.hidden=true},3200)}
function status(t,w=false){$('status').innerHTML=t;$('status').classList.toggle('warn',w);if(w)notice($('status').textContent)}
async function diag(){let perm='unavailable',policy='unknown';try{if(navigator.permissions?.query)perm=(await navigator.permissions.query({name:'microphone'})).state}catch{}try{if(document.permissionsPolicy?.allowsFeature)policy=document.permissionsPolicy.allowsFeature('microphone')?'allowed':'blocked';else if(document.featurePolicy?.allowsFeature)policy=document.featurePolicy.allowsFeature('microphone')?'allowed':'blocked'}catch{}const framed=top!==self;$('diag').textContent=`secure context: ${isSecureContext?'yes':'NO'}\nembedded frame: ${framed?'YES':'no'}\nframe mic policy: ${policy}\nsite mic permission: ${perm}\ngetUserMedia: ${navigator.mediaDevices?.getUserMedia?'available':'UNAVAILABLE'}\norigin: ${location.origin}`;$('standaloneBtn').classList.toggle('show',framed||policy==='blocked');}
function micError(e){if(!isSecureContext)return'Microphone needs a normal HTTPS page.';if(e?.name==='NotAllowedError'||e?.name==='PermissionDeniedError')return top!==self?'This embedded viewer blocked microphone access before Chrome could ask. Open this page directly in Chrome.':'Chrome denied microphone access for this site.';if(e?.name==='NotFoundError')return'No microphone was found.';if(e?.name==='NotReadableError')return'The microphone exists but could not be read; another app may be using it.';return`Microphone failed${e?.message?': '+e.message:''}.`}
async function ask(){try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('getUserMedia unavailable');const s=await navigator.mediaDevices.getUserMedia({audio:true,video:false});s.getTracks().forEach(t=>t.stop());status('Chrome granted microphone permission. Tap <b>Mic on</b>.');notice('Microphone permission granted.',true)}catch(e){status(micError(e),true)}finally{diag()}}
async function toggleMic(){if(mic){stopMic();return}stopDemo();try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});ac=new (window.AudioContext||window.webkitAudioContext)();await ac.resume();analyser=ac.createAnalyser();analyser.fftSize=2048;analyser.smoothingTimeConstant=.15;source=ac.createMediaStreamSource(stream);source.connect(analyser);mic=true;$('micBtn').textContent='Mic off';$('micBtn').classList.add('active');$('modePill').textContent='MIC';status('Microphone active. Speak normally; the voice meter should move.');notice('Microphone connected.',true)}catch(e){status(micError(e),true);diag()}}
function stopMic(){mic=false;stream?.getTracks().forEach(t=>t.stop());stream=null;source=null;analyser=null;ac?.close().catch(()=>{});ac=null;$('micBtn').textContent='Mic on';$('micBtn').classList.remove('active');if(!demo)$('modePill').textContent='IDLE'}
function toggleDemo(){demo?stopDemo():(stopMic(),demo=true,$('demoBtn').textContent='Stop demo',$('demoBtn').classList.add('active'),$('modePill').textContent='DEMO',status('Demo voice active.'))}
function stopDemo(){demo=false;$('demoBtn').textContent='Demo voice';$('demoBtn').classList.remove('active');if(!mic)$('modePill').textContent='IDLE'}
function audio(now){if(mic&&analyser){analyser.getByteTimeDomainData(td);let s=0;for(const v of td){const x=(v-128)/128;s+=x*x}level=Math.sqrt(s/td.length);analyser.getByteFrequencyData(fd);let m=0,w=0;for(let i=1;i<fd.length;i++){const v=fd[i]/255;m+=v;w+=v*i}centroid=m?(w/m)/(fd.length-1):.5}else if(demo){const syll=Math.max(0,Math.sin(now*.008))*.55+Math.max(0,Math.sin(now*.019+1.3))*.28;level=.012+syll*.085*((Math.sin(now*.00135)+Math.sin(now*.0005+2)>-.45)?1:.08);centroid=.43+Math.sin(now*.0043)*.22+Math.sin(now*.0011)*.12}else{level=0;centroid=.5}smooth=smooth*(+c.smoothing.value)+level*(1-(+c.smoothing.value));}
function mouth(now){const raw=Math.max(0,smooth*24*(+c.sensitivity.value)-.035),open=Math.min(1,Math.pow(raw,.72))*(+c.mouthEx.value),talk=open>.045,sp=talk?Math.max(0,(centroid-.38)*1.9):0,ro=talk?Math.max(0,(.62-centroid)*1.6)*(+c.roundness.value):0,p=Math.sin(now*.027)*.06;let w=(50+sp*22-ro*16)*(+c.mouthWidth.value),h=4+open*(42+ro*15-sp*7)+p*20;w=Math.max(26,w);h=Math.max(3,h);let shape='REST';if(talk)shape=open>.72?'OPEN':ro>.28?'O / U':sp>.28?'E / I':open>.22?'SPEECH':'M / B / P';$('shapePill').textContent=shape;const cx=300,cy=392,l=cx-w,r=cx+w,t=cy-h*.55,b=cy+h*.6;svg.mouth.setAttribute('d',`M${l} ${cy} Q${cx} ${t} ${r} ${cy} Q${cx} ${b} ${l} ${cy}Z`);svg.teeth.setAttribute('d',`M${l+8} ${cy} Q${cx} ${cy-h*.28} ${r-8} ${cy} Q${cx} ${cy+Math.max(1,h*.03)} ${l+8} ${cy}Z`);svg.teeth.style.opacity=talk&&open>.28?Math.min(.72,sp*.65+open*.25):0;svg.chin.style.transform=`translateY(${Math.min(15,open*14)}px)`;return Math.min(1.25,open)}
function geometry(){const hw=+c.headWidth.value,hl=+c.headLength.value;svg.head.setAttribute('transform',`translate(${300-300*hw} ${306-306*hl}) scale(${hw} ${hl})`);svg.glow.setAttribute('transform',`translate(${300-300*hw} ${306-306*hl}) scale(${hw} ${hl})`);svg.hair.setAttribute('transform',`translate(${300-300*hw} 0) scale(${hw} 1)`);const off=(+c.eyeSpacing.value-1)*48,sz=+c.eyeSize.value,bh=+c.browHeight.value;svg.eyeL.setAttribute('transform',`translate(${-off} 0) translate(${234-234*sz} ${266-266*sz}) scale(${sz})`);svg.eyeR.setAttribute('transform',`translate(${off} 0) translate(${366-366*sz} ${266-266*sz}) scale(${sz})`);svg.lidL.setAttribute('transform',`translate(${-off} 0) translate(${234-234*sz} ${266-266*sz}) scale(${sz})`);svg.lidR.setAttribute('transform',`translate(${off} 0) translate(${366-366*sz} ${266-266*sz}) scale(${sz})`);svg.browL.setAttribute('transform',`translate(${-off} ${bh})`);svg.browR.setAttribute('transform',`translate(${off} ${bh})`);}
function life(now,dt,open){if(now>nextBlink&&!blinkDir)blinkDir=1;if(blinkDir===1){blink=Math.min(1,blink+dt/85);if(blink>=1)blinkDir=-1}else if(blinkDir===-1){blink=Math.max(0,blink-dt/120);if(blink<=0){blinkDir=0;nextBlink=now+(1200+Math.random()*3400)/(+c.blinkRate.value)}}svg.lidL.style.opacity=blink;svg.lidR.style.opacity=blink;if(now>nextEye){const e=+c.eyeMotion.value;targetX=(Math.random()-.5)*10*e;targetY=(Math.random()-.5)*6*e;nextEye=now+600+Math.random()*1900}eyeX+=(targetX-eyeX)*.035;eyeY+=(targetY-eyeY)*.035;const off=(+c.eyeSpacing.value-1)*48,sz=+c.eyeSize.value;svg.irisL.setAttribute('transform',`translate(${-off+eyeX} ${eyeY}) scale(${sz}) translate(${234/sz-234} ${266/sz-266})`);svg.irisR.setAttribute('transform',`translate(${off+eyeX} ${eyeY}) scale(${sz}) translate(${366/sz-366} ${266/sz-266})`);const hm=+c.headMotion.value,nudge=open*hm;const rot=Math.sin(now*.00072)*1.1*hm+Math.sin(now*.0033)*.18*nudge,tx=Math.sin(now*.00055+1.4)*3.2*hm,ty=Math.sin(now*.00081)*2.2*hm-nudge*1.8;svg.headGroup.style.transform=`translate(${tx}px,${ty}px) rotate(${rot}deg)`}
function tick(now){const dt=Math.min(50,now-last);last=now;audio(now);const o=mouth(now);life(now,dt,o);$('meterFill').style.width=`${Math.min(100,smooth*6200*(+c.sensitivity.value))}%`;requestAnimationFrame(tick)}
ids.forEach(id=>c[id].addEventListener('input',()=>{outputs();geometry()}));
$('permissionBtn').addEventListener('click',ask);$('permissionDiagBtn').addEventListener('click',ask);$('micBtn').addEventListener('click',toggleMic);$('demoBtn').addEventListener('click',toggleDemo);$('diagBtn').addEventListener('click',diag);$('standaloneBtn').addEventListener('click',()=>window.open(location.href,'_blank','noopener'));$('standaloneDiagBtn').addEventListener('click',()=>window.open(location.href,'_blank','noopener'));
const presets={neutral:{headWidth:1,headLength:1,eyeSpacing:1,eyeSize:1,mouthWidth:1,browHeight:0},angular:{headWidth:.9,headLength:1.1,eyeSpacing:1.08,eyeSize:.9,mouthWidth:.92,browHeight:-8},soft:{headWidth:1.12,headLength:.94,eyeSpacing:.94,eyeSize:1.13,mouthWidth:1.12,browHeight:6}};
qs('[data-preset]').forEach(b=>b.addEventListener('click',()=>{Object.entries(presets[b.dataset.preset]).forEach(([k,v])=>c[k].value=v);outputs();geometry()}));
$('randomBtn').addEventListener('click',()=>{const r=(a,b)=>a+Math.random()*(b-a),v={headWidth:r(.78,1.22),headLength:r(.85,1.17),eyeSpacing:r(.78,1.28),eyeSize:r(.8,1.3),mouthWidth:r(.76,1.34),browHeight:r(-18,18)};Object.entries(v).forEach(([k,x])=>c[k].value=x);outputs();geometry()});
$('resetBtn').addEventListener('click',()=>{Object.entries(defaults).forEach(([k,v])=>c[k].value=v);outputs();geometry()});
const aside=$('controls'),scrim=$('scrim');function drawer(on){aside.classList.toggle('open',on);scrim.classList.toggle('show',on)}$('drawerBtn').addEventListener('click',()=>drawer(!aside.classList.contains('open')));scrim.addEventListener('click',()=>drawer(false));
outputs();geometry();diag();requestAnimationFrame(tick);
})();
