import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { OBJLoader } from 'three/addons/loaders/OBJLoader.js';

const $=id=>document.getElementById(id), clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)), lerp=(a,b,t)=>a+(b-a)*t;
const SENTENCE='Father packed five bright blue puppets in a good box, then Joe chose three sheep by the old gate.';

const WORDS=[
 ['Father',[['f','FF'],['ɑː','aa'],['ð','TH'],['ə','aa']]],
 ['packed',[['p','PP'],['æ','E'],['k','kk'],['t','DD']]],
 ['five',[['f','FF'],['aɪ','aa>I'],['v','FF']]],
 ['bright',[['b','PP'],['r','RR'],['aɪ','aa>I'],['t','DD']]],
 ['blue',[['b','PP'],['l','nn'],['uː','U']]],
 ['puppets',[['p','PP'],['ʌ','aa'],['p','PP'],['ɪ','I'],['t','DD'],['s','SS']]],
 ['in',[['ɪ','I'],['n','nn']]],
 ['a',[['ə','aa']]],
 ['good',[['g','kk'],['ʊ','U'],['d','DD']]],
 ['box',[['b','PP'],['ɒ','O'],['k','kk'],['s','SS']]],
 ['then',[['ð','TH'],['ɛ','E'],['n','nn']]],
 ['Joe',[['dʒ','CH'],['əʊ','aa>U']]],
 ['chose',[['tʃ','CH'],['əʊ','aa>U'],['z','SS']]],
 ['three',[['θ','TH'],['r','RR'],['iː','I']]],
 ['sheep',[['ʃ','CH'],['iː','I'],['p','PP']]],
 ['by',[['b','PP'],['aɪ','aa>I']]],
 ['the',[['ð','TH'],['ə','aa']]],
 ['old',[['əʊ','aa>U'],['l','nn'],['d','DD']]],
 ['gate',[['g','kk'],['eɪ','E>I'],['t','DD']]],
];

const MORPH_FILES={
 jawOpen:'jawOpen.obj',jawForward:'jawForward.obj',mouthFunnel:'mouthFunnel.obj',mouthPucker:'mouthPucker.obj',
 mouthPress_L:'mouthPress_L.obj',mouthPress_R:'mouthPress_R.obj',mouthDimple_L:'mouthDimple_L.obj',mouthDimple_R:'mouthDimple_R.obj',
 mouthRollLower:'mouthRollLower.obj',mouthRollUpper:'mouthRollUpper.obj',mouthUpperUp_L:'mouthUpperUp_L.obj',mouthUpperUp_R:'mouthUpperUp_R.obj',
 mouthShrugUpper:'mouthShrugUpper.obj',mouthLowerDown_L:'mouthLowerDown_L.obj',mouthLowerDown_R:'mouthLowerDown_R.obj',
 mouthStretch_L:'mouthStretch_L.obj',mouthStretch_R:'mouthStretch_R.obj'
};
const MORPH_KEYS=Object.keys(MORPH_FILES), MORPHS=MORPH_KEYS.map(k=>MORPH_FILES[k]), MI=Object.fromEntries(MORPH_KEYS.map((k,i)=>[k,i]));
const blankMorphs=()=>Object.fromEntries(MORPH_KEYS.map(k=>[k,0]));
const P={
 sil:{},
 aa:{jawOpen:.72,mouthDimple_L:.12,mouthDimple_R:.12},
 E:{jawOpen:.38,mouthStretch_L:.66,mouthStretch_R:.66,mouthDimple_L:.35,mouthDimple_R:.35},
 I:{jawOpen:.20,mouthStretch_L:.95,mouthStretch_R:.95,mouthDimple_L:.28,mouthDimple_R:.28},
 O:{jawOpen:.42,mouthPucker:.72,mouthFunnel:.86,jawForward:.30},
 U:{jawOpen:.16,mouthPucker:1,mouthFunnel:.66,jawForward:.18},
 PP:{jawOpen:.03,mouthRollLower:.88,mouthRollUpper:.88,mouthPress_L:.82,mouthPress_R:.82,mouthUpperUp_L:.24,mouthUpperUp_R:.24},
 FF:{jawOpen:.16,mouthRollLower:.82,mouthPucker:.25,mouthDimple_L:.50,mouthDimple_R:.50,mouthShrugUpper:.62,mouthLowerDown_L:.16,mouthLowerDown_R:.16},
 TH:{jawOpen:.22,mouthRollUpper:.42,mouthLowerDown_L:.28,mouthLowerDown_R:.28},
 DD:{jawOpen:.14,mouthPress_L:.34,mouthPress_R:.34,mouthStretch_L:.22,mouthStretch_R:.22},
 kk:{jawOpen:.22,mouthLowerDown_L:.24,mouthLowerDown_R:.24,mouthDimple_L:.14,mouthDimple_R:.14},
 SS:{jawOpen:.08,mouthStretch_L:.68,mouthStretch_R:.68,mouthPress_L:.22,mouthPress_R:.22,mouthLowerDown_L:.18,mouthLowerDown_R:.18},
 nn:{jawOpen:.14,mouthDimple_L:.18,mouthDimple_R:.18,mouthPress_L:.10,mouthPress_R:.10},
 RR:{jawOpen:.18,mouthPucker:.18,mouthFunnel:.36,jawForward:.18},
 CH:{jawOpen:.16,mouthPucker:.28,mouthFunnel:.46,mouthPress_L:.18,mouthPress_R:.18}
};
function poseFor(vis){if(vis.includes('>')){const [a,b]=vis.split('>'),A=P[a]||P.sil,B=P[b]||P.sil,o=blankMorphs();for(const k of MORPH_KEYS)o[k]=lerp(A[k]||0,B[k]||0,.55);return o}return {...blankMorphs(),...(P[vis]||{})}}

let duration=8.8, segments=[], selected=0, audioBuffer=null, audioBlob=null, audioUrl=null, recorder=null, recStream=null, recTimer=null, speed=1;
function buildTemplate(){const flat=[];for(const [word,phones] of WORDS)for(const [phone,viseme] of phones)flat.push({word,phone,viseme,strength:1});const pad=.28,usable=Math.max(.5,duration-pad*2);const weights=flat.map(s=>/[ɑæʌɒɔʊuiɪɛə]|ː|əʊ|aɪ|eɪ/.test(s.phone)?1.45:(['p','b','t','d','k','g'].includes(s.phone)?0.65:1));const total=weights.reduce((a,b)=>a+b,0);let t=pad;segments=flat.map((s,i)=>{const d=usable*weights[i]/total,out={...s,start:t,end:t+d};t+=d;return out});selected=0;renderAll()}
function renderSentence(){const box=$('sentence');box.innerHTML='';WORDS.forEach(([w],i)=>{const s=document.createElement('span');s.className='word';s.dataset.word=w;s.textContent=w+(i<WORDS.length-1?' ':'');box.append(s)})}
function groupWords(){const map=[];for(let i=0;i<segments.length;){const w=segments[i].word,start=segments[i].start;let j=i+1;while(j<segments.length&&segments[j].word===w)j++;map.push({word:w,start,end:segments[j-1].end});i=j}return map}
function pct(t){return duration?100*t/duration:0}
function renderTimeline(){const lane=$('timeline'),words=$('wordLane');lane.innerHTML='';words.innerHTML='';for(const g of groupWords()){const d=document.createElement('div');d.className='wordBlock';d.dataset.word=g.word;d.style.left=pct(g.start)+'%';d.style.width=(pct(g.end)-pct(g.start))+'%';d.textContent=g.word;words.append(d)}segments.forEach((s,i)=>{const d=document.createElement('div');d.className='seg'+(i===selected?' selected':'');d.dataset.index=i;d.style.left=pct(s.start)+'%';d.style.width=Math.max(.15,pct(s.end)-pct(s.start))+'%';d.innerHTML=`<b>${s.phone}</b><small>${s.viseme} · ${Math.round((s.end-s.start)*1000)}ms</small>`;d.addEventListener('click',e=>{if(e.target.classList.contains('handle'))return;selectSegment(i)});if(i<segments.length-1){const h=document.createElement('div');h.className='handle';h.addEventListener('pointerdown',e=>startBoundaryDrag(e,i));d.append(h)}lane.append(d)})}
function renderInspector(){const s=segments[selected];if(!s)return;$('selWord').value=s.word;$('selPhone').value=s.phone;$('visemeSelect').value=s.viseme;$('strength').value=s.strength;$('strengthOut').textContent=s.strength.toFixed(2);$('startMs').value=Math.round(s.start*1000);$('endMs').value=Math.round(s.end*1000)}
function renderAll(){renderSentence();renderTimeline();renderInspector();updateActive(audio.currentTime||0)}
function selectSegment(i){selected=clamp(i,0,segments.length-1);renderTimeline();renderInspector();const s=segments[selected];audio.currentTime=clamp(audio.currentTime,s.start,s.end);updateActive(audio.currentTime)}
function startBoundaryDrag(e,i){e.preventDefault();e.stopPropagation();const el=$('timeline'),rect=el.getBoundingClientRect(),minGap=.018;const move=ev=>{const x=clamp(ev.clientX-rect.left,0,rect.width),t=x/rect.width*duration,lo=segments[i].start+minGap,hi=segments[i+1].end-minGap,b=clamp(t,lo,hi);segments[i].end=b;segments[i+1].start=b;renderTimeline();renderInspector()};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
function setBoundary(i,which,t){if(which==='start'){if(i===0)return;const b=clamp(t,segments[i-1].start+.018,segments[i].end-.018);segments[i].start=b;segments[i-1].end=b}else{if(i===segments.length-1)return;const b=clamp(t,segments[i].start+.018,segments[i+1].end-.018);segments[i].end=b;segments[i+1].start=b}renderTimeline();renderInspector()}

const audio=$('audio');
function setAudioBlob(blob,reset=true){if(audioUrl)URL.revokeObjectURL(audioUrl);audioBlob=blob;audioUrl=URL.createObjectURL(blob);audio.src=audioUrl;audio.onloadedmetadata=async()=>{duration=audio.duration||duration;$('playBtn').disabled=false;$('rewBtn').disabled=false;$('fwdBtn').disabled=false;$('exportBtn').disabled=false;if(reset)buildTemplate();await drawWave(blob);showNotice(`Audio ready · ${duration.toFixed(2)}s`)};audio.load()}
async function drawWave(blob){try{const ctx=new AudioContext(),ab=await blob.arrayBuffer(),buf=await ctx.decodeAudioData(ab.slice(0));audioBuffer=buf;drawWaveCanvas();await ctx.close()}catch(e){console.warn(e)}}
function drawWaveCanvas(){const cv=$('wave'),wrap=$('waveWrap'),dpr=Math.min(devicePixelRatio,2),w=Math.max(300,wrap.clientWidth),h=wrap.clientHeight;cv.width=w*dpr;cv.height=h*dpr;const g=cv.getContext('2d');g.scale(dpr,dpr);g.clearRect(0,0,w,h);g.fillStyle='#070609';g.fillRect(0,0,w,h);if(!audioBuffer)return;const x=audioBuffer.getChannelData(0),step=Math.max(1,Math.floor(x.length/w));g.strokeStyle='#ff5260';g.globalAlpha=.78;g.beginPath();for(let px=0;px<w;px++){let mn=1,mx=-1;for(let j=0;j<step;j++){const v=x[px*step+j]||0;mn=Math.min(mn,v);mx=Math.max(mx,v)}const y1=h/2-mx*h*.42,y2=h/2-mn*h*.42;g.moveTo(px,y1);g.lineTo(px,y2)}g.stroke();g.globalAlpha=.25;g.strokeStyle='#fff';g.beginPath();g.moveTo(0,h/2);g.lineTo(w,h/2);g.stroke()}
window.addEventListener('resize',drawWaveCanvas);$('waveWrap').addEventListener('pointerdown',e=>{if(!duration)return;const r=e.currentTarget.getBoundingClientRect();audio.currentTime=clamp((e.clientX-r.left)/r.width*duration,0,duration);updateActive(audio.currentTime)});
async function startRecord(){if(recorder){stopRecord();return}try{recStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});const mime=['audio/webm;codecs=opus','audio/webm'].find(t=>MediaRecorder.isTypeSupported(t))||'',chunks=[];recorder=new MediaRecorder(recStream,mime?{mimeType:mime}:undefined);recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.onstop=()=>{const type=recorder?.mimeType||mime||'audio/webm',b=new Blob(chunks,{type});recorder=null;recStream?.getTracks().forEach(t=>t.stop());recStream=null;$('recordBtn').textContent='RECORD SENTENCE';$('recordBtn').classList.remove('selected');clearTimeout(recTimer);setAudioBlob(b)};recorder.start(150);$('recordBtn').textContent='STOP RECORDING';$('recordBtn').classList.add('selected');showNotice('Recording — say the sentence naturally');recTimer=setTimeout(stopRecord,14000)}catch(e){showNotice(e.message||'Microphone failed')}}
function stopRecord(){if(recorder&&recorder.state!=='inactive')recorder.stop()}
$('recordBtn').onclick=startRecord;
function togglePlay(){if(!audio.src)return;if(audio.paused){audio.playbackRate=speed;audio.play()}else audio.pause()}
$('playBtn').onclick=togglePlay;audio.addEventListener('play',()=>{$('playBtn').textContent='PAUSE'});audio.addEventListener('pause',()=>{$('playBtn').textContent='PLAY'});audio.addEventListener('ended',()=>{$('playBtn').textContent='PLAY'});$('rewBtn').onclick=()=>audio.currentTime=clamp(audio.currentTime-.1,0,duration);$('fwdBtn').onclick=()=>audio.currentTime=clamp(audio.currentTime+.1,0,duration);$('audioFile').onchange=e=>{const f=e.target.files?.[0];if(f)setAudioBlob(f);e.target.value=''};
function currentIndex(t){let lo=0,hi=segments.length-1;while(lo<=hi){const m=(lo+hi)>>1,s=segments[m];if(t<s.start)hi=m-1;else if(t>=s.end)lo=m+1;else return m}return clamp(lo,0,segments.length-1)}
function mixPose(a,b,t){const o=blankMorphs();for(const k of MORPH_KEYS)o[k]=lerp(a[k]||0,b[k]||0,t);return o}
function sampleAt(t){if(!segments.length||t<segments[0].start||t>segments.at(-1).end)return{pose:blankMorphs(),i:-1};const i=currentIndex(t),s=segments[i],blend=(+$('blend').value)/1000;let pose=poseFor(s.viseme),strength=s.strength;if(blend>0){const dl=t-s.start,dr=s.end-t;if(dl<blend&&i>0){const u=.5+.5*clamp(dl/blend);pose=mixPose(poseFor(segments[i-1].viseme),pose,u);strength=lerp(segments[i-1].strength,strength,u)}if(dr<blend&&i<segments.length-1){const u=.5+.5*clamp(dr/blend);pose=mixPose(pose,poseFor(segments[i+1].viseme),u);strength=lerp(strength,segments[i+1].strength,u)}}for(const k of MORPH_KEYS)pose[k]=clamp((pose[k]||0)*strength);return{pose,i}}

const FACEKIT='https://cdn.jsdelivr.net/gh/USC-ICT/ICT-FaceKit@master/FaceXModel/';
const canvas=$('stage'),renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x040406,1);renderer.outputColorSpace=THREE.SRGBColorSpace;const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x050507,.014);const camera=new THREE.PerspectiveCamera(34,1,.1,500);camera.position.set(0,-.3,43);const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.065;controls.enablePan=false;controls.minDistance=24;controls.maxDistance=80;controls.target.set(0,.6,3);scene.add(new THREE.HemisphereLight(0x7b1d27,0x050507,.7));const key=new THREE.DirectionalLight(0xff4d5d,1.55);key.position.set(-7,10,16);scene.add(key);const rim=new THREE.DirectionalLight(0x63101b,.95);rim.position.set(12,2,-10);scene.add(rim);const headRig=new THREE.Group();scene.add(headRig);
function grid(size=110,div=11){const p=[],h=size/2,g=new THREE.BufferGeometry();for(let i=0;i<=div;i++){const t=-h+size*i/div;p.push(-h,0,t,h,0,t,t,0,-h,t,0,h)}g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));return new THREE.LineSegments(g,new THREE.LineBasicMaterial({color:0x53131b,transparent:true,opacity:.15}))}const floor=grid();floor.position.set(0,-14,-10);scene.add(floor);const back=grid();back.rotation.x=Math.PI/2;back.position.set(0,18,-28);back.material.opacity=.06;scene.add(back);const loader=new OBJLoader(),loadObj=n=>new Promise((res,rej)=>loader.load(FACEKIT+n,res,undefined,rej)),meshList=r=>{const a=[];r.traverse(o=>o.isMesh&&a.push(o));return a},materialsOf=m=>Array.isArray(m)?m:[m];let baseMeshes=[],renderMeshes=[],faceReady=false;
function solidMaterial(base){const n=String(materialsOf(base.material)[0]?.name||'').toLowerCase();let color=0x440b12,em=0x250307,rough=.72;if(n.includes('sclera')){color=0x85515a;em=0x150305;rough=.5}else if(n.includes('iris')){color=0x160206;em=0x080001}else if(n.includes('teeth')){color=0x8b6c70;em=0x140708;rough=.55}else if(n.includes('gum')||n.includes('tongue')||n.includes('mouth')){color=0x30040a;em=0x170105}return new THREE.MeshStandardMaterial({color,emissive:em,roughness:rough,metalness:.04,transparent:true,opacity:.28})}
function prep(root){baseMeshes=meshList(root);for(const b of baseMeshes){if(!b.geometry.attributes.normal)b.geometry.computeVertexNormals();b.geometry.morphAttributes=b.geometry.morphAttributes||{};b.geometry.morphAttributes.position=[];b.geometry.morphTargetsRelative=false}}
function attach(root,index){const ts=meshList(root);let matched=0;baseMeshes.forEach((b,i)=>{const t=(b.name&&ts.find(m=>m.name===b.name&&m.geometry.attributes.position.count===b.geometry.attributes.position.count))||ts[i];if(!t||t.geometry.attributes.position.count!==b.geometry.attributes.position.count)return;b.geometry.morphAttributes.position[index]=t.geometry.attributes.position.clone();matched++});if(!matched)throw new Error('No compatible geometry for '+MORPHS[index])}
function buildHead(){for(const b of baseMeshes){const h=new THREE.Group();h.position.copy(b.position);h.rotation.copy(b.rotation);h.scale.copy(b.scale);const solid=new THREE.Mesh(b.geometry,solidMaterial(b)),wire=new THREE.Mesh(b.geometry,new THREE.MeshBasicMaterial({color:0xff2638,wireframe:true,transparent:true,opacity:.31,depthWrite:false}));solid.updateMorphTargets();wire.updateMorphTargets();wire.renderOrder=2;h.add(solid,wire);headRig.add(h);renderMeshes.push({solid,wire})}const box=new THREE.Box3().setFromObject(headRig),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),sc=22/Math.max(size.x,size.y);headRig.scale.setScalar(sc);headRig.position.set(-center.x*sc,-center.y*sc+.8,-center.z*sc+2.8)}
async function boot(){try{$('headStatus').textContent='LOADING NEUTRAL';prep(await loadObj('generic_neutral_mesh.obj'));for(let i=0;i<MORPHS.length;i++){$('headStatus').textContent=`LOADING MOUTH ${i+1}/${MORPHS.length}`;attach(await loadObj(MORPHS[i]),i);await new Promise(r=>requestAnimationFrame(r))}buildHead();faceReady=true;$('headStatus').textContent='HEAD READY'}catch(e){console.error(e);$('headStatus').textContent='HEAD LOAD FAILED'}}
let morph=blankMorphs();function applyPose(target){for(const k of MORPH_KEYS)morph[k]=lerp(morph[k],target[k]||0,.34);if(faceReady)for(const {solid,wire} of renderMeshes)for(const m of [solid,wire])if(m.morphTargetInfluences)for(const k of MORPH_KEYS)m.morphTargetInfluences[MI[k]]=morph[k];for(const k of MORPH_KEYS){const e=$('m_'+k);if(e)e.style.width=clamp(morph[k])*100+'%'}}
function makeMorphRows(){const box=$('morphs');for(const k of MORPH_KEYS){const d=document.createElement('div');d.className='morphRow';d.innerHTML=`<span>${k}</span><i><em id="m_${k}"></em></i>`;box.append(d)}}makeMorphRows();
function updateActive(t){const {i}=sampleAt(t),x=duration?clamp(t/duration):0;$('waveHead').style.left=x*100+'%';$('timeRead').textContent=`${t.toFixed(3)} / ${duration.toFixed(3)} s`;$('hudMs').textContent=Math.round(t*1000)+' ms';document.querySelectorAll('.seg').forEach((e,j)=>e.classList.toggle('active',j===i));document.querySelectorAll('.wordBlock,.sentence .word').forEach(e=>e.classList.toggle('active',i>=0&&e.dataset.word===segments[i]?.word));if(i>=0){$('hudWord').textContent=segments[i].word;$('hudPhone').textContent=segments[i].phone;$('hudViseme').textContent=segments[i].viseme}else{$('hudWord').textContent='—';$('hudPhone').textContent='—';$('hudViseme').textContent='REST'}}
function resize(){const w=canvas.clientWidth,h=canvas.clientHeight,dpr=renderer.getPixelRatio();if(canvas.width!==Math.floor(w*dpr)||canvas.height!==Math.floor(h*dpr)){renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}}
function loop(){requestAnimationFrame(loop);resize();controls.update();const t=audio.currentTime||0,sm=sampleAt(t);applyPose(sm.pose);updateActive(t);renderer.render(scene,camera)}
function setView(n){const v={front:[0,-.3,43],three:[22,1,36],side:[39,.5,5]}[n];camera.position.set(...v);controls.target.set(0,.6,3);controls.update()}document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
for(const v of ['sil','PP','FF','TH','DD','kk','SS','nn','RR','CH','aa','E','I','O','U','aa>I','aa>U','E>I']){const o=document.createElement('option');o.value=v;o.textContent=v;$('visemeSelect').append(o)}
$('visemeSelect').onchange=e=>{segments[selected].viseme=e.target.value;renderTimeline()};$('strength').oninput=e=>{segments[selected].strength=+e.target.value;$('strengthOut').textContent=(+e.target.value).toFixed(2);renderTimeline()};$('startMs').onchange=e=>setBoundary(selected,'start',+e.target.value/1000);$('endMs').onchange=e=>setBoundary(selected,'end',+e.target.value/1000);$('startHere').onclick=()=>setBoundary(selected,'start',audio.currentTime);$('endHere').onclick=()=>setBoundary(selected,'end',audio.currentTime);$('blend').oninput=e=>$('blendOut').textContent=e.target.value+' ms';$('blendOut').textContent=$('blend').value+' ms';document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>{speed=+b.dataset.speed;audio.playbackRate=speed;document.querySelectorAll('[data-speed]').forEach(x=>x.classList.toggle('selected',x===b))});$('resetBtn').onclick=()=>{if(confirm('Reset every phoneme boundary to the proportional template?'))buildTemplate()};
async function blobToDataURL(blob){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(blob)})}
$('exportBtn').onclick=async()=>{if(!audioBlob)return;const project={format:'voice-face-gold-timeline-v1',createdAt:new Date().toISOString(),sentence:SENTENCE,duration,blendMs:+$('blend').value,segments:segments.map(s=>({...s})),audio:{mimeType:audioBlob.type,dataUrl:await blobToDataURL(audioBlob)}};const b=new Blob([JSON.stringify(project)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`gold-lipsync-${new Date().toISOString().replace(/[:.]/g,'-')}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
$('projectFile').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const p=JSON.parse(await f.text());if(p.format!=='voice-face-gold-timeline-v1')throw new Error('Not a gold timeline project');const savedSegments=p.segments.map(s=>({...s})),savedDuration=p.duration;$('blend').value=p.blendMs??70;$('blendOut').textContent=$('blend').value+' ms';const r=await fetch(p.audio.dataUrl),b=await r.blob();setAudioBlob(b,false);audio.onloadedmetadata=async()=>{duration=savedDuration;segments=savedSegments;selected=0;$('playBtn').disabled=false;$('rewBtn').disabled=false;$('fwdBtn').disabled=false;$('exportBtn').disabled=false;await drawWave(b);renderAll();showNotice('Project restored')};audio.load()}catch(err){showNotice(err.message)}e.target.value=''};
function showNotice(t){const n=$('notice');n.textContent=t;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),2600)}
window.addEventListener('keydown',e=>{if(['INPUT','SELECT'].includes(document.activeElement?.tagName))return;if(e.code==='Space'){e.preventDefault();togglePlay()}else if(e.key==='ArrowLeft'){e.preventDefault();audio.currentTime=clamp(audio.currentTime-.02,0,duration)}else if(e.key==='ArrowRight'){e.preventDefault();audio.currentTime=clamp(audio.currentTime+.02,0,duration)}});
renderSentence();buildTemplate();boot();requestAnimationFrame(loop);
