const COMMIT='d3af5f9ff86ab6b2b1913d411a4e1922ec101953';
const BASE=`https://cdn.jsdelivr.net/gh/met4citizen/HeadAudio@${COMMIT}`;
const MODULE_URL=`${BASE}/dist/headaudio.min.mjs`;
const WORKLET_URL=`${BASE}/dist/headworklet.min.mjs`;
const MODEL_URL=`${BASE}/dist/model-en-mixed.bin`;
const STORAGE='voice-face-headaudio-personal-v1';
const $=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t;
const names=['aa','E','I','O','U','PP','SS','TH','DD','FF','kk','nn','RR','CH','sil'];
const keys=names.map(v=>`viseme_${v}`),weights=Object.fromEntries(keys.map(k=>[k,0])),bars={};
const trainable=[
  {name:'aa',label:'AA / AH',prompt:'AHHH — as in father',code:'a'},
  {name:'E',label:'E / EH',prompt:'EHHH — as in bed',code:'e'},
  {name:'I',label:'I / EE',prompt:'EEEE — as in see',code:'i'},
  {name:'O',label:'O / OH',prompt:'OHHH — as in go',code:'o'},
  {name:'U',label:'U / OO',prompt:'OOOO — as in food',code:'u'},
  {name:'FF',label:'F / V',prompt:'FFFFF — steady airflow',code:'f'},
  {name:'SS',label:'S / Z',prompt:'SSSSS — steady hiss',code:'s'},
  {name:'TH',label:'TH',prompt:'THHHH — as in thin',code:'t'},
  {name:'nn',label:'N',prompt:'NNNNN — sustained n',code:'n'},
  {name:'RR',label:'R',prompt:'RRRRR — your natural r',code:'r'},
  {name:'CH',label:'SH / CH',prompt:'SHHHH — steady sh sound',code:'c'}
].map(x=>({...x,viseme:names.indexOf(x.name),group:240+names.indexOf(x.name)}));
let HeadAudio=null,libError=null,audioCtx=null,stream=null,source=null,node=null,mic=false;
let activeIndex=14,lastDistances=null,lastVadDb=-100,lastVadActive=false,last=performance.now();
let capture=null,personal=loadPersonal();
const libReady=import(MODULE_URL).then(m=>HeadAudio=m.HeadAudio).catch(e=>{libError=e;console.error(e)});
function loadPersonal(){try{return JSON.parse(localStorage.getItem(STORAGE)||'{"prototypes":{},"speakerMean":150}')}catch{return{prototypes:{},speakerMean:150}}}
function savePersonal(){localStorage.setItem(STORAGE,JSON.stringify(personal));updateTrainUI()}
function notice(t,ok=false,ms=2600){const n=$('notice');n.textContent=t;n.hidden=false;n.classList.toggle('ok',ok);if(ms)setTimeout(()=>{if(n.textContent===t)n.hidden=true},ms)}
function status(t,w=false){$('status').innerHTML=t;$('status').classList.toggle('warn',w);if(w)notice($('status').textContent)}
function friendly(e){if(e?.name==='NotAllowedError')return'Microphone permission was denied for this site.';if(e?.name==='NotFoundError')return'No microphone was found.';return e?.message||'HeadAudio could not start.'}
for(const name of names){const label=document.createElement('div');label.className='viseme-name';label.textContent=name;const bar=document.createElement('div');bar.className='viseme-bar';const fill=document.createElement('span');bar.append(fill);$('visemeGrid').append(label,bar);bars[name]={label,fill}}
for(const t of trainable){const b=document.createElement('button');b.className='train-btn';b.dataset.name=t.name;b.innerHTML=`<b>${t.label}</b><span>${t.prompt}</span>`;b.onclick=()=>beginCapture(t);$('trainGrid').append(b)}
function updateTrainUI(){let n=0;for(const t of trainable){const p=personal.prototypes?.[t.name],b=document.querySelector(`.train-btn[data-name="${t.name}"]`);b.classList.toggle('ready',!!p);if(p){n++;b.querySelector('span').textContent=`trained · ${p.samples} vectors · tap to replace`}else b.querySelector('span').textContent=t.prompt} $('profilePill').textContent=n?`MY VOICE ${n}`:'STOCK';$('trainReadout').textContent=n?`${n} personal prototype${n===1?'':'s'} saved locally. HeadAudio keeps its stock model as fallback for everything else.`:'No personal prototypes yet.'}
updateTrainUI();
async function diagnostics(){let perm='unavailable';try{if(navigator.permissions?.query)perm=(await navigator.permissions.query({name:'microphone'})).state}catch{}$('diag').textContent=[`secure context: ${isSecureContext?'yes':'NO'}`,`site mic permission: ${perm}`,`HeadAudio: ${libError?'FAILED':HeadAudio?'loaded':'loading…'}`,`personal prototypes: ${Object.keys(personal.prototypes||{}).length}`,`feature capture: ${capture?'ACTIVE':'idle'}`,`source: HeadAudio @ ${COMMIT.slice(0,8)}`].join('\n')}
async function ask(){try{const s=await navigator.mediaDevices.getUserMedia({audio:true});s.getTracks().forEach(t=>t.stop());notice('Microphone permission granted.',true)}catch(e){status(friendly(e),true)}diagnostics()}
function setParam(name,value){if(node){const p=node.parameters.get(name);if(p)p.value=+value}}
function syncControls(){for(const [id,suffix] of [['speakerMean',''],['vadActive',' dB'],['vadInactive',' dB']])$(id+'Out').textContent=$(id).value+suffix;$('silSensitivityOut').textContent=(+$('silSensitivity').value).toFixed(2);setParam('speakerMeanHz',$('speakerMean').value);setParam('vadGateActiveDb',$('vadActive').value);setParam('vadGateInactiveDb',$('vadInactive').value);setParam('silSensitivity',$('silSensitivity').value)}
$('speakerMean').value=personal.speakerMean||150;['speakerMean','vadActive','vadInactive','silSensitivity'].forEach(id=>$(id).addEventListener('input',()=>{syncControls();if(id==='speakerMean'){personal.speakerMean=+$('speakerMean').value;savePersonal()}}));syncControls();
function applyPrototype(p){if(!node||!p)return;node.port.postMessage({event:'model',model:[{phoneme:p.code,group:p.group,viseme:p.viseme,mu:new Float32Array(p.mu),sigmaInvLower:new Float32Array(p.sigmaInvLower)}]})}
function applySaved(){if(!node){status('Turn the microphone on first.',true);return}for(const p of Object.values(personal.prototypes||{}))applyPrototype(p);notice('Personal prototypes applied.',true);status('Personal model layered over the stock HeadAudio model.')}
async function toggleMic(){if(mic){stopMic();return}$('micBtn').disabled=true;$('micBtn').textContent='Starting…';try{await libReady;if(!HeadAudio)throw libError||new Error('HeadAudio failed to load');stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});audioCtx=new AudioContext();await audioCtx.resume();await audioCtx.audioWorklet.addModule(WORKLET_URL);node=new HeadAudio(audioCtx,{processorOptions:{vadEventsEnabled:true,featureEventsEnabled:true,visemeEventsEnabled:true},parameterData:{vadMode:1,vadGateActiveDb:+$('vadActive').value,vadGateInactiveDb:+$('vadInactive').value,silMode:1,silCalibrationWindowSec:3,silSensitivity:+$('silSensitivity').value,speakerMeanHz:+$('speakerMean').value}});await node.loadModel(MODEL_URL);node.onvalue=(k,v)=>{if(k in weights)weights[k]=clamp(v,0,1)};node.onvad=o=>{lastVadDb=Number.isFinite(o.db)?o.db:lastVadDb;lastVadActive=!!o.active};node.onviseme=o=>{if(Number.isInteger(o.viseme))activeIndex=o.viseme;lastDistances=Array.isArray(o.distances)?o.distances:null};node.onfeature=o=>{if(capture&&o?.vector?.length===12)capture.records.push({vector:Array.from(o.vector),le:o.le||0})};node.onstarted=()=>{$('modePill').textContent='SPEECH'};node.onended=()=>{$('modePill').textContent='MIC'};node.oncalibrated=o=>{ $('silenceBtn').disabled=false;$('silenceBtn').textContent='Calibrate 3s of silence';if(o?.error)status(`Silence calibration failed: ${o.error}`,true);else notice('Silence calibration complete.',true)};source=audioCtx.createMediaStreamSource(stream);source.connect(node);mic=true;applySaved();$('micBtn').textContent='Mic off';$('micBtn').classList.add('active');$('modePill').textContent='MIC';notice('HeadAudio training mode connected.',true);status('Start with silence calibration, then train AA and one consonant to see whether personal prototypes help.')}catch(e){console.error(e);status(friendly(e),true);stopMic(false)}finally{$('micBtn').disabled=false;diagnostics()}}
function stopMic(update=true){if(capture)finishCapture(false);mic=false;try{source?.disconnect()}catch{};try{node?.disconnect()}catch{};stream?.getTracks().forEach(t=>t.stop());source=node=stream=null;audioCtx?.close().catch(()=>{});audioCtx=null;for(const k of keys)weights[k]=0;$('micBtn').textContent='Mic on';$('micBtn').classList.remove('active');$('modePill').textContent='IDLE';if(update)status('Microphone stopped.')}
function calibrateSilence(){if(!node){status('Turn the microphone on first.',true);return}$('silenceBtn').disabled=true;$('silenceBtn').textContent='Stay quiet…';status('Stay quiet for HeadAudio’s three-second silence calibration.');node.calibrate()}
async function beginCapture(t){if(!node){status('Turn the microphone on before training.',true);return}if(capture)return;const b=document.querySelector(`.train-btn[data-name="${t.name}"]`);capture={target:t,records:[],button:b,oldVad:node.parameters.get('vadMode').value};b.classList.add('recording');for(const x of document.querySelectorAll('.train-btn'))x.disabled=true;status(`Get ready: ${t.prompt}`);notice(`Get ready… ${t.label}`,false,0);setParam('vadMode',0);await new Promise(r=>setTimeout(r,550));if(!capture)return;status(`GO — ${t.prompt}`);$('notice').textContent=`GO — ${t.prompt}`;setTimeout(()=>finishCapture(true),1750)}
function finishCapture(commit){if(!capture)return;const c=capture;capture=null;setParam('vadMode',c.oldVad??1);c.button.classList.remove('recording');for(const x of document.querySelectorAll('.train-btn'))x.disabled=false;$('notice').hidden=true;if(!commit)return;const records=c.records.filter(r=>Array.isArray(r.vector)&&r.vector.length===12);records.sort((a,b)=>b.le-a.le);const keep=records.slice(0,Math.min(96,Math.max(18,Math.floor(records.length*.78))));if(keep.length<14){status(`Not enough usable ${c.target.label} frames (${keep.length}). Try again a little louder/steadier.`,true);return}try{const vectors=keep.map(r=>new Float32Array(r.vector));const q=node.training.computePrototype(c.target.code,c.target.group,c.target.viseme,vectors);const p={name:c.target.name,code:c.target.code,group:c.target.group,viseme:c.target.viseme,mu:Array.from(q.mu),sigmaInvLower:Array.from(q.sigmaInvLower),samples:vectors.length,speakerMean:+$('speakerMean').value,created:Date.now()};personal.prototypes[c.target.name]=p;personal.speakerMean=+$('speakerMean').value;savePersonal();applyPrototype(p);notice(`${c.target.label} trained from ${vectors.length} frames.`,true);status(`${c.target.label} personal prototype is live. Say a few words containing that sound and compare it with the stock behaviour.`)}catch(e){console.error(e);status(`Training failed: ${e.message}`,true)}diagnostics()}
function clearPersonal(){personal={prototypes:{},speakerMean:+$('speakerMean').value};localStorage.removeItem(STORAGE);updateTrainUI();notice('Saved personal model cleared. Restart the mic to return to stock-only classification.',true);status('Personal model cleared. Toggle the microphone off/on to remove already-loaded personal prototypes from this session.')}
const poses={aa:{o:.92,w:.57,r:0},E:{o:.42,w:.77,r:0},I:{o:.24,w:.82,r:0},O:{o:.62,w:.40,r:.88},U:{o:.22,w:.29,r:1},PP:{o:.02,w:.48,r:0},SS:{o:.20,w:.72,r:0},TH:{o:.22,w:.61,r:0},DD:{o:.30,w:.62,r:0},FF:{o:.12,w:.57,r:0},kk:{o:.38,w:.56,r:0},nn:{o:.25,w:.61,r:0},RR:{o:.40,w:.55,r:.15},CH:{o:.24,w:.66,r:.08},sil:{o:.02,w:.5,r:0}};
const mouth=$('mouth'),upper=$('upperLip'),lower=$('lowerLip'),teeth=$('teeth'),tongue=$('tongue'),chin=$('chin');let ms={o:.02,w:.5,r:0};
function renderMouth(){let t={o:0,w:0,r:0},sum=0;for(const n of names){const v=weights[`viseme_${n}`]||0;if(v){sum+=v;const p=poses[n];t.o+=p.o*v;t.w+=p.w*v;t.r+=p.r*v}}if(sum<.001)t={...poses.sil};else{t.o/=sum;t.w/=sum;t.r/=sum}for(const k in ms)ms[k]=lerp(ms[k],t[k],.3);const width=clamp(34+ms.w*44-ms.r*12,22,92),height=clamp(2+ms.o*52,1.5,62),cx=300,cy=392,l=cx-width,r=cx+width,top=cy-height*(.47+.08*ms.r),bot=cy+height*(.60+.05*ms.o);mouth.setAttribute('d',`M ${l} ${cy} Q ${cx} ${top} ${r} ${cy} Q ${cx} ${bot} ${l} ${cy}Z`);upper.setAttribute('d',`M ${l} ${cy} Q ${cx} ${top-1.4} ${r} ${cy}`);lower.setAttribute('d',`M ${l} ${cy} Q ${cx} ${bot+1.5} ${r} ${cy}`);teeth.style.opacity=(activeIndex===6||activeIndex===9)?.6:0;tongue.style.opacity=(activeIndex===7||activeIndex===11)?.6:0;chin.style.transform=`translateY(${Math.min(15,ms.o*13)}px)`}
function updateStats(){const active=names[clamp(activeIndex,0,14)]||'sil';$('activeViseme').textContent=active;$('shapePill').textContent=active.toUpperCase();$('vadDb').textContent=Number.isFinite(lastVadDb)?`${lastVadDb.toFixed(1)} dB`:'— dB';$('vadState').textContent=lastVadActive?'active':'inactive';$('meterFill').style.width=`${clamp((lastVadDb+70)/45*100,0,100)}%`;let gap=null;if(lastDistances?.length>1){const s=lastDistances.filter(Number.isFinite).slice().sort((a,b)=>a-b);if(s.length>1)gap=s[1]-s[0]}$('confidence').textContent=gap==null?'—':gap.toFixed(1);for(const n of names){const v=weights[`viseme_${n}`]||0;bars[n].fill.style.width=`${v*100}%`;bars[n].label.classList.toggle('active',n===active)}}
function tick(t){const dt=Math.min(50,t-last);last=t;if(node)node.update(dt);renderMouth();updateStats();requestAnimationFrame(tick)}
$('permissionBtn').onclick=ask;$('permissionDiagBtn').onclick=ask;$('micBtn').onclick=toggleMic;$('silenceBtn').onclick=calibrateSilence;$('diagBtn').onclick=diagnostics;$('applySavedBtn').onclick=applySaved;$('clearBtn').onclick=clearPersonal;const aside=$('controls'),scrim=$('scrim');function drawer(on){aside.classList.toggle('open',on);scrim.classList.toggle('show',on)}$('drawerBtn').onclick=()=>drawer(!aside.classList.contains('open'));scrim.onclick=()=>drawer(false);
diagnostics();libReady.finally(diagnostics);requestAnimationFrame(tick);
