import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {OBJLoader} from 'three/addons/loaders/OBJLoader.js';
const $=id=>document.getElementById(id),clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t;
const SENTENCE='Father packed five bright blue puppets in a good box, then Joe chose three sheep by the old gate.';
const WORDS=[['Father',[['f','FF'],['ɑː','aa'],['ð','TH'],['ə','aa']]],['packed',[['p','PP'],['æ','E'],['k','kk'],['t','DD']]],['five',[['f','FF'],['aɪ','aa>I'],['v','FF']]],['bright',[['b','PP'],['r','RR'],['aɪ','aa>I'],['t','DD']]],['blue',[['b','PP'],['l','nn'],['uː','U']]],['puppets',[['p','PP'],['ʌ','aa'],['p','PP'],['ɪ','I'],['t','DD'],['s','SS']]],['in',[['ɪ','I'],['n','nn']]],['a',[['ə','aa']]],['good',[['g','kk'],['ʊ','U'],['d','DD']]],['box',[['b','PP'],['ɒ','O'],['k','kk'],['s','SS']]],['then',[['ð','TH'],['ɛ','E'],['n','nn']]],['Joe',[['dʒ','CH'],['əʊ','aa>U']]],['chose',[['tʃ','CH'],['əʊ','aa>U'],['z','SS']]],['three',[['θ','TH'],['r','RR'],['iː','I']]],['sheep',[['ʃ','CH'],['iː','I'],['p','PP']]],['by',[['b','PP'],['aɪ','aa>I']]],['the',[['ð','TH'],['ə','aa']]],['old',[['əʊ','aa>U'],['l','nn'],['d','DD']]],['gate',[['g','kk'],['eɪ','E>I'],['t','DD']]]];
const MORPH_FILES={jawOpen:'jawOpen.obj',jawForward:'jawForward.obj',mouthFunnel:'mouthFunnel.obj',mouthPucker:'mouthPucker.obj',mouthPress_L:'mouthPress_L.obj',mouthPress_R:'mouthPress_R.obj',mouthDimple_L:'mouthDimple_L.obj',mouthDimple_R:'mouthDimple_R.obj',mouthRollLower:'mouthRollLower.obj',mouthRollUpper:'mouthRollUpper.obj',mouthUpperUp_L:'mouthUpperUp_L.obj',mouthUpperUp_R:'mouthUpperUp_R.obj',mouthShrugUpper:'mouthShrugUpper.obj',mouthLowerDown_L:'mouthLowerDown_L.obj',mouthLowerDown_R:'mouthLowerDown_R.obj',mouthStretch_L:'mouthStretch_L.obj',mouthStretch_R:'mouthStretch_R.obj'};
const MORPH_KEYS=Object.keys(MORPH_FILES),MORPHS=MORPH_KEYS.map(k=>MORPH_FILES[k]),MI=Object.fromEntries(MORPH_KEYS.map((k,i)=>[k,i]));
const blank=()=>Object.fromEntries(MORPH_KEYS.map(k=>[k,0]));
const P={sil:{},aa:{jawOpen:.72,mouthDimple_L:.12,mouthDimple_R:.12},E:{jawOpen:.38,mouthStretch_L:.66,mouthStretch_R:.66,mouthDimple_L:.35,mouthDimple_R:.35},I:{jawOpen:.20,mouthStretch_L:.95,mouthStretch_R:.95,mouthDimple_L:.28,mouthDimple_R:.28},O:{jawOpen:.42,mouthPucker:.72,mouthFunnel:.86,jawForward:.30},U:{jawOpen:.16,mouthPucker:1,mouthFunnel:.66,jawForward:.18},PP:{jawOpen:.03,mouthRollLower:.88,mouthRollUpper:.88,mouthPress_L:.82,mouthPress_R:.82,mouthUpperUp_L:.24,mouthUpperUp_R:.24},FF:{jawOpen:.16,mouthRollLower:.82,mouthPucker:.25,mouthDimple_L:.50,mouthDimple_R:.50,mouthShrugUpper:.62,mouthLowerDown_L:.16,mouthLowerDown_R:.16},TH:{jawOpen:.22,mouthRollUpper:.42,mouthLowerDown_L:.28,mouthLowerDown_R:.28},DD:{jawOpen:.14,mouthPress_L:.34,mouthPress_R:.34,mouthStretch_L:.22,mouthStretch_R:.22},kk:{jawOpen:.22,mouthLowerDown_L:.24,mouthLowerDown_R:.24,mouthDimple_L:.14,mouthDimple_R:.14},SS:{jawOpen:.08,mouthStretch_L:.68,mouthStretch_R:.68,mouthPress_L:.22,mouthPress_R:.22,mouthLowerDown_L:.18,mouthLowerDown_R:.18},nn:{jawOpen:.14,mouthDimple_L:.18,mouthDimple_R:.18,mouthPress_L:.10,mouthPress_R:.10},RR:{jawOpen:.18,mouthPucker:.18,mouthFunnel:.36,jawForward:.18},CH:{jawOpen:.16,mouthPucker:.28,mouthFunnel:.46,mouthPress_L:.18,mouthPress_R:.18}};
function mixPose(a,b,t){const o=blank();for(const k of MORPH_KEYS)o[k]=lerp(a[k]||0,b[k]||0,t);return o}
function poseFor(vis,phase=.5){if(vis.includes('>')){const[a,b]=vis.split('>');return mixPose(P[a]||{},P[b]||{},clamp(phase))}return {...blank(),...(P[vis]||{})}}
const audio=$('audio');let duration=0,segments=[],selected=0,audioBlob=null,audioUrl=null,audioBuffer=null,recorder=null,recStream=null,speed=1,tapMode=false,tapMarks=[];
function phoneWeight(p){if(/[ɑæʌɒɔʊuiɪɛə]|ː|əʊ|aɪ|eɪ/.test(p))return 1.45;if(['p','b','t','d','k','g'].includes(p))return .65;return 1}
function makeFallback(){const pad=.25,usable=Math.max(.5,(duration||8.8)-pad*2),all=[];WORDS.forEach(([w,ps])=>ps.forEach(([p,v])=>all.push({word:w,phone:p,viseme:v,strength:1})));const tw=all.reduce((a,s)=>a+phoneWeight(s.phone),0);let t=pad;segments=all.map(s=>{const d=usable*phoneWeight(s.phone)/tw,out={...s,start:t,end:t+d};t+=d;return out});selected=0;renderAll()}
function buildFromWordMarks(marks){segments=[];for(let wi=0;wi<WORDS.length;wi++){const[word,ps]=WORDS[wi],start=marks[wi],end=marks[wi+1],weights=ps.map(([p])=>phoneWeight(p)),tw=weights.reduce((a,b)=>a+b,0);let t=start;for(let pi=0;pi<ps.length;pi++){const[p,v]=ps[pi],d=(end-start)*weights[pi]/tw;segments.push({word,phone:p,viseme:v,strength:1,start:t,end:t+d});t+=d}}selected=0;renderAll()}
function renderSentence(){const b=$('sentence');b.innerHTML='';WORDS.forEach(([w],i)=>{const s=document.createElement('span');s.dataset.word=w;s.textContent=w+(i<WORDS.length-1?' ':'');b.append(s)})}
function pct(t){return duration?100*t/duration:0}
function groupWords(){const out=[];for(let i=0;i<segments.length;){const word=segments[i].word,start=segments[i].start;let j=i+1;while(j<segments.length&&segments[j].word===word)j++;out.push({word,start,end:segments[j-1].end});i=j}return out}
function renderTimeline(){const ph=$('phones'),wl=$('wordLane');ph.innerHTML='';wl.innerHTML='';for(const g of groupWords()){const e=document.createElement('div');e.className='word';e.dataset.word=g.word;e.style.left=pct(g.start)+'%';e.style.width=(pct(g.end)-pct(g.start))+'%';e.textContent=g.word;wl.append(e)}segments.forEach((s,i)=>{const e=document.createElement('div');e.className='seg'+(i===selected?' sel':'');e.dataset.index=i;e.style.left=pct(s.start)+'%';e.style.width=Math.max(.15,pct(s.end)-pct(s.start))+'%';e.innerHTML=`<b>${s.phone}</b><small>${s.viseme}<br>${Math.round((s.end-s.start)*1000)}ms</small>`;e.onclick=ev=>{if(!ev.target.classList.contains('handle'))selectSeg(i)};if(i<segments.length-1){const h=document.createElement('div');h.className='handle';h.onpointerdown=ev=>dragBoundary(ev,i);e.append(h)}ph.append(e)})}
function renderInspector(){const s=segments[selected];if(!s)return;$('selWord').value=s.word;$('selPhone').value=s.phone;$('viseme').value=s.viseme;$('strength').value=s.strength;$('strengthOut').textContent=s.strength.toFixed(2);$('startMs').value=Math.round(s.start*1000);$('endMs').value=Math.round(s.end*1000)}
function renderAll(){renderTimeline();renderInspector();updateActive(audio.currentTime||0)}
function selectSeg(i){selected=clamp(i,0,segments.length-1);renderTimeline();renderInspector()}
function dragBoundary(e,i){e.preventDefault();e.stopPropagation();const r=$('phones').getBoundingClientRect(),min=.018,move=ev=>{const t=clamp((ev.clientX-r.left)/r.width,0,1)*duration,b=clamp(t,segments[i].start+min,segments[i+1].end-min);segments[i].end=b;segments[i+1].start=b;renderTimeline();renderInspector()},up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
function setBoundary(i,which,t){if(which==='start'){if(i===0)return;const b=clamp(t,segments[i-1].start+.018,segments[i].end-.018);segments[i].start=b;segments[i-1].end=b}else{if(i===segments.length-1)return;const b=clamp(t,segments[i].start+.018,segments[i+1].end-.018);segments[i].end=b;segments[i+1].start=b}renderAll()}
function currentIndex(t){if(!segments.length)return-1;let lo=0,hi=segments.length-1;while(lo<=hi){const m=(lo+hi)>>1,s=segments[m];if(t<s.start)hi=m-1;else if(t>=s.end)lo=m+1;else return m}return-1}
function sampleAt(t){const i=currentIndex(t);if(i<0)return{pose:blank(),i:-1};const s=segments[i],phase=(t-s.start)/Math.max(.001,s.end-s.start),blend=(+$('blend').value)/1000;let pose=poseFor(s.viseme,phase),strength=s.strength;if(blend>0){const dl=t-s.start,dr=s.end-t;if(dl<blend&&i>0){const prev=segments[i-1],u=.5+.5*clamp(dl/blend);pose=mixPose(poseFor(prev.viseme,1),pose,u);strength=lerp(prev.strength,strength,u)}if(dr<blend&&i<segments.length-1){const nxt=segments[i+1],u=.5+.5*clamp(dr/blend);pose=mixPose(pose,poseFor(nxt.viseme,0),u);strength=lerp(strength,nxt.strength,u)}}for(const k of MORPH_KEYS)pose[k]=clamp((pose[k]||0)*strength);return{pose,i}}
async function setAudio(blob,reset=true){if(audioUrl)URL.revokeObjectURL(audioUrl);audioBlob=blob;audioUrl=URL.createObjectURL(blob);audio.src=audioUrl;audio.onloadedmetadata=async()=>{duration=audio.duration||8.8;$('play').disabled=false;$('back').disabled=false;$('forward').disabled=false;$('tapAlign').disabled=false;$('export').disabled=false;if(reset)makeFallback();await drawWave(blob);$('tapStatus').textContent=`Audio ready · ${duration.toFixed(2)}s · tap-align the words next.`};audio.load()}
async function drawWave(blob){try{const ctx=new AudioContext(),ab=await blob.arrayBuffer();audioBuffer=await ctx.decodeAudioData(ab.slice(0));drawWaveCanvas();await ctx.close()}catch(e){console.warn(e)}}
function drawWaveCanvas(){const c=$('wave'),w=$('waveWrap'),dpr=Math.min(devicePixelRatio,2),W=Math.max(300,w.clientWidth),H=w.clientHeight;c.width=W*dpr;c.height=H*dpr;const g=c.getContext('2d');g.scale(dpr,dpr);g.fillStyle='#070609';g.fillRect(0,0,W,H);if(!audioBuffer)return;const x=audioBuffer.getChannelData(0),step=Math.max(1,Math.floor(x.length/W));g.strokeStyle='#ff5260';g.beginPath();for(let px=0;px<W;px++){let mn=1,mx=-1;for(let j=0;j<step;j++){const v=x[px*step+j]||0;mn=Math.min(mn,v);mx=Math.max(mx,v)}g.moveTo(px,H/2-mx*H*.42);g.lineTo(px,H/2-mn*H*.42)}g.stroke()}
window.addEventListener('resize',drawWaveCanvas);$('waveWrap').onpointerdown=e=>{if(!duration)return;const r=e.currentTarget.getBoundingClientRect();audio.currentTime=clamp((e.clientX-r.left)/r.width*duration,0,duration);updateActive(audio.currentTime)};
async function startRecord(){if(recorder){if(recorder.state!=='inactive')recorder.stop();return}try{recStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});const types=['audio/webm;codecs=opus','audio/webm'];const mime=types.find(t=>window.MediaRecorder?.isTypeSupported?.(t))||'',chunks=[];recorder=new MediaRecorder(recStream,mime?{mimeType:mime}:undefined);recorder.ondataavailable=e=>e.data?.size&&chunks.push(e.data);recorder.onstop=()=>{const type=recorder.mimeType||mime||'audio/webm',b=new Blob(chunks,{type});recorder=null;recStream?.getTracks().forEach(t=>t.stop());recStream=null;$('record').textContent='RECORD SENTENCE';$('record').classList.remove('sel');setAudio(b,true)};recorder.start(200);$('record').textContent='STOP RECORDING';$('record').classList.add('sel');$('tapStatus').textContent='Recording. Say the sentence naturally, then tap STOP.'}catch(e){$('tapStatus').textContent=e.message||'Microphone failed'}}
$('record').onclick=startRecord;
function togglePlay(){if(!audio.src)return;if(audio.paused){audio.playbackRate=speed;audio.play().catch(e=>$('tapStatus').textContent=e.message)}else audio.pause()}
$('play').onclick=togglePlay;$('back').onclick=()=>audio.currentTime=clamp(audio.currentTime-.1,0,duration);$('forward').onclick=()=>audio.currentTime=clamp(audio.currentTime+.1,0,duration);audio.onplay=()=>$('play').textContent='PAUSE';audio.onpause=()=>$('play').textContent='PLAY';audio.onended=()=>$('play').textContent='PLAY';
$('audioFile').onchange=e=>{const f=e.target.files?.[0];if(f)setAudio(f,true);e.target.value=''};
function startTapAlign(){if(!audio.src)return;tapMode=true;tapMarks=[];audio.pause();audio.currentTime=0;$('tapWord').hidden=false;$('tapWord').textContent='TAP: '+WORDS[0][0];$('tapStatus').textContent='Press play automatically, then tap each word as you hear its START.';audio.playbackRate=.75;speed=.75;audio.play().catch(()=>{});$('tapAlign').disabled=true}
function tapNext(){if(!tapMode)return;tapMarks.push(audio.currentTime);const n=tapMarks.length;if(n<WORDS.length){$('tapWord').textContent='TAP: '+WORDS[n][0];$('tapStatus').textContent=`${n}/${WORDS.length} word starts marked`}else if(n===WORDS.length){$('tapWord').textContent='TAP: END';$('tapStatus').textContent='Tap once more just after the final T in “gate”.'}else{finishTapAlign()}}
function finishTapAlign(){tapMode=false;audio.pause();$('tapWord').hidden=true;$('tapAlign').disabled=false;if(tapMarks.length<WORDS.length+1)return;for(let i=1;i<tapMarks.length;i++)tapMarks[i]=Math.max(tapMarks[i],tapMarks[i-1]+.03);tapMarks[tapMarks.length-1]=Math.min(duration,tapMarks[tapMarks.length-1]);buildFromWordMarks(tapMarks);$('tapStatus').textContent='Word alignment built. Press PLAY. Fine-tune only the phonemes that look wrong.'}
$('tapAlign').onclick=startTapAlign;$('tapWord').onclick=tapNext;
for(const v of ['sil','PP','FF','TH','DD','kk','SS','nn','RR','CH','aa','E','I','O','U','aa>I','aa>U','E>I']){const o=document.createElement('option');o.value=v;o.textContent=v;$('viseme').append(o)}
$('viseme').onchange=e=>{segments[selected].viseme=e.target.value;renderTimeline()};$('strength').oninput=e=>{segments[selected].strength=+e.target.value;$('strengthOut').textContent=(+e.target.value).toFixed(2)};$('startMs').onchange=e=>setBoundary(selected,'start',+e.target.value/1000);$('endMs').onchange=e=>setBoundary(selected,'end',+e.target.value/1000);$('blend').oninput=e=>$('blendOut').textContent=e.target.value+'ms';document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>{speed=+b.dataset.speed;audio.playbackRate=speed;document.querySelectorAll('[data-speed]').forEach(x=>x.classList.toggle('sel',x===b))});
async function blobToDataURL(blob){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(blob)})}
$('export').onclick=async()=>{if(!audioBlob)return;const p={format:'voice-face-gold-timeline-v2',createdAt:new Date().toISOString(),sentence:SENTENCE,duration,blendMs:+$('blend').value,segments:segments.map(s=>({...s})),audio:{mimeType:audioBlob.type,dataUrl:await blobToDataURL(audioBlob)}};const b=new Blob([JSON.stringify(p)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='gold-lipsync-v2-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
$('projectFile').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const p=JSON.parse(await f.text());if(p.format!=='voice-face-gold-timeline-v2')throw new Error('Not a V2 gold timeline project');const b=await(await fetch(p.audio.dataUrl)).blob(),saved=p.segments.map(s=>({...s}));await setAudio(b,false);const wait=()=>{if(!Number.isFinite(audio.duration)||!audio.duration)return requestAnimationFrame(wait);duration=p.duration;segments=saved;selected=0;$('blend').value=p.blendMs??55;$('blendOut').textContent=$('blend').value+'ms';renderAll();$('tapStatus').textContent='Project restored'};wait()}catch(err){$('tapStatus').textContent=err.message}e.target.value=''};
function updateActive(t){const{i}=sampleAt(t),x=duration?clamp(t/duration):0;$('waveHead').style.left=x*100+'%';$('time').textContent=`${t.toFixed(3)} / ${duration.toFixed(3)}s`;$('hudMs').textContent=Math.round(t*1000)+'ms';document.querySelectorAll('.seg').forEach((e,j)=>e.classList.toggle('active',j===i));document.querySelectorAll('.word,.sentence span').forEach(e=>e.classList.toggle('active',i>=0&&e.dataset.word===segments[i]?.word));if(i>=0){$('hudWord').textContent=segments[i].word;$('hudPhone').textContent=segments[i].phone;$('hudVis').textContent=segments[i].viseme}else{$('hudWord').textContent='—';$('hudPhone').textContent='—';$('hudVis').textContent='REST'}}
const FACEKIT='https://cdn.jsdelivr.net/gh/USC-ICT/ICT-FaceKit@master/FaceXModel/';const canvas=$('stage'),renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x040406);renderer.outputColorSpace=THREE.SRGBColorSpace;const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.1,500);camera.position.set(0,-.3,43);const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.enablePan=false;controls.target.set(0,.6,3);controls.minDistance=24;controls.maxDistance=80;scene.add(new THREE.HemisphereLight(0x7b1d27,0x050507,.7));const key=new THREE.DirectionalLight(0xff4d5d,1.5);key.position.set(-7,10,16);scene.add(key);const rig=new THREE.Group();scene.add(rig);const loader=new OBJLoader(),loadObj=n=>new Promise((res,rej)=>loader.load(FACEKIT+n,res,undefined,rej)),meshList=r=>{const a=[];r.traverse(o=>o.isMesh&&a.push(o));return a};let bases=[],renders=[],ready=false;
function mat(b){const n=String((Array.isArray(b.material)?b.material[0]:b.material)?.name||'').toLowerCase();let c=0x440b12,e=0x250307;if(n.includes('sclera')){c=0x85515a;e=0x150305}else if(n.includes('iris')){c=0x160206;e=0x080001}else if(n.includes('teeth')){c=0x8b6c70;e=0x140708}else if(n.includes('mouth')||n.includes('gum')||n.includes('tongue')){c=0x30040a;e=0x170105}return new THREE.MeshStandardMaterial({color:c,emissive:e,roughness:.7,transparent:true,opacity:.28})}
function prep(r){bases=meshList(r);for(const b of bases){if(!b.geometry.attributes.normal)b.geometry.computeVertexNormals();b.geometry.morphAttributes.position=[];b.geometry.morphTargetsRelative=false}}
function attach(r,ix){const ts=meshList(r);bases.forEach((b,i)=>{const t=(b.name&&ts.find(x=>x.name===b.name&&x.geometry.attributes.position.count===b.geometry.attributes.position.count))||ts[i];if(t&&t.geometry.attributes.position.count===b.geometry.attributes.position.count)b.geometry.morphAttributes.position[ix]=t.geometry.attributes.position.clone()})}
function build(){for(const b of bases){const h=new THREE.Group();h.position.copy(b.position);h.rotation.copy(b.rotation);h.scale.copy(b.scale);const solid=new THREE.Mesh(b.geometry,mat(b)),wire=new THREE.Mesh(b.geometry,new THREE.MeshBasicMaterial({color:0xff2638,wireframe:true,transparent:true,opacity:.3,depthWrite:false}));solid.updateMorphTargets();wire.updateMorphTargets();h.add(solid,wire);rig.add(h);renders.push({solid,wire})}const box=new THREE.Box3().setFromObject(rig),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),sc=22/Math.max(size.x,size.y);rig.scale.setScalar(sc);rig.position.set(-center.x*sc,-center.y*sc+.8,-center.z*sc+2.8)}
async function boot(){try{$('headStatus').textContent='LOADING NEUTRAL';prep(await loadObj('generic_neutral_mesh.obj'));for(let i=0;i<MORPHS.length;i++){$('headStatus').textContent=`LOADING MOUTH ${i+1}/${MORPHS.length}`;attach(await loadObj(MORPHS[i]),i);await new Promise(r=>requestAnimationFrame(r))}build();ready=true;$('headStatus').textContent='HEAD READY'}catch(e){console.error(e);$('headStatus').textContent='HEAD LOAD FAILED'}}
let morph=blank();function applyPose(p){for(const k of MORPH_KEYS)morph[k]=lerp(morph[k],p[k]||0,.38);if(ready)for(const {solid,wire} of renders)for(const m of [solid,wire])if(m.morphTargetInfluences)for(const k of MORPH_KEYS)m.morphTargetInfluences[MI[k]]=morph[k];for(const k of MORPH_KEYS){const e=$('m_'+k);if(e)e.style.width=clamp(morph[k])*100+'%'}}
function morphRows(){for(const k of MORPH_KEYS){const d=document.createElement('div');d.className='morph';d.innerHTML=`<span>${k}</span><i><em id="m_${k}"></em></i>`;$('morphs').append(d)}}morphRows();
function resize(){const w=canvas.clientWidth,h=canvas.clientHeight,d=renderer.getPixelRatio();if(canvas.width!==Math.floor(w*d)||canvas.height!==Math.floor(h*d)){renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}}
function loop(){requestAnimationFrame(loop);resize();controls.update();const s=sampleAt(audio.currentTime||0);applyPose(s.pose);updateActive(audio.currentTime||0);renderer.render(scene,camera)}
renderSentence();makeFallback();boot();requestAnimationFrame(loop);