const COMMIT='d3af5f9ff86ab6b2b1913d411a4e1922ec101953';
const BASE=`https://cdn.jsdelivr.net/gh/met4citizen/HeadAudio@${COMMIT}`;
const MODULE_URL=`${BASE}/dist/headaudio.min.mjs`,WORKLET_URL=`${BASE}/dist/headworklet.min.mjs`,MODEL_URL=`${BASE}/dist/model-en-mixed.bin`;
const STORAGE='voice-face-headaudio-personal-v1', PREFIX='vx2:';
const $=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,sleep=ms=>new Promise(r=>setTimeout(r,ms));
const names=['aa','E','I','O','U','PP','SS','TH','DD','FF','kk','nn','RR','CH','sil'],keys=names.map(v=>`viseme_${v}`),weights=Object.fromEntries(keys.map(k=>[k,0])),bars={};
const visemeIndex=n=>names.indexOf(n);
const mono=[
 {key:'fleece',word:'FLEECE',ipa:'/iː/',example:'see',hint:'Hold only the vowel from “see”.',v:'I',code:'f1',group:100},
 {key:'kit',word:'KIT',ipa:'/ɪ/',example:'ink / sit',hint:'Hold the vowel you use in “ink”.',v:'I',code:'k1',group:101},
 {key:'dress',word:'DRESS',ipa:'/ɛ/',example:'bed',hint:'Hold the vowel from “bed”.',v:'E',code:'d1',group:102},
 {key:'trap',word:'TRAP',ipa:'/æ/',example:'cat',hint:'Hold the vowel from “cat”.',v:'E',code:'t1',group:103},
 {key:'strut',word:'STRUT',ipa:'/ʌ/',example:'cup',hint:'Hold the vowel from “cup”.',v:'aa',code:'s1',group:104},
 {key:'father',word:'FATHER',ipa:'/ɑː/',example:'father',hint:'Hold the first vowel from “father”.',v:'aa',code:'f2',group:105},
 {key:'lot',word:'LOT',ipa:'/ɒ/',example:'lot',hint:'Hold the vowel from “lot”.',v:'O',code:'l1',group:106},
 {key:'thought',word:'THOUGHT',ipa:'/ɔː/',example:'thought',hint:'Hold the vowel from “thought”.',v:'O',code:'t2',group:107},
 {key:'foot',word:'FOOT',ipa:'/ʊ/',example:'foot',hint:'Hold the vowel from “foot”.',v:'U',code:'f3',group:108},
 {key:'goose',word:'GOOSE',ipa:'/uː/',example:'food / goose',hint:'Hold the vowel from “food”.',v:'U',code:'g1',group:109},
 {key:'comma',word:'COMMA',ipa:'/ə/',example:'comma',hint:'Hold a relaxed schwa, like the final vowel in “comma”.',v:'aa',code:'c1',group:110}
].map(x=>({...x,viseme:visemeIndex(x.v),store:`${PREFIX}mono:${x.key}`}));
const diph=[
 {key:'face',word:'FACE',ipa:'/eɪ/',example:'hey / face',hint:'Stretch the vowel from “hey”: let it move naturally.',start:'E',end:'I',codeA:'a1',codeB:'a2',groupA:160,groupB:161},
 {key:'price',word:'PRICE',ipa:'/aɪ/',example:'high / price',hint:'Stretch the vowel from “high” from beginning to end.',start:'aa',end:'I',codeA:'b1',codeB:'b2',groupA:162,groupB:163},
 {key:'choice',word:'CHOICE',ipa:'/ɔɪ/',example:'boy / choice',hint:'Stretch the vowel from “boy”.',start:'O',end:'I',codeA:'c2',codeB:'c3',groupA:164,groupB:165},
 {key:'goat',word:'GOAT',ipa:'/əʊ/',example:'go / goat',hint:'Stretch the vowel from “go” through its full movement.',start:'aa',end:'U',codeA:'d2',codeB:'d3',groupA:166,groupB:167},
 {key:'mouth',word:'MOUTH',ipa:'/aʊ/',example:'now / mouth',hint:'Stretch the vowel from “now”.',start:'aa',end:'U',codeA:'e1',codeB:'e2',groupA:168,groupB:169}
].map(x=>({...x,startViseme:visemeIndex(x.start),endViseme:visemeIndex(x.end),storeA:`${PREFIX}diph:${x.key}:start`,storeB:`${PREFIX}diph:${x.key}:end`}));
let HeadAudio=null,libError=null,audioCtx=null,stream=null,source=null,node=null,mic=false,capture=null,guideRunning=false;
let activeIndex=14,lastDistances=null,lastVadDb=-100,lastVadActive=false,last=performance.now();
let personal=loadPersonal();
const libReady=import(MODULE_URL).then(m=>HeadAudio=m.HeadAudio).catch(e=>{libError=e;console.error(e)});
function loadPersonal(){try{const p=JSON.parse(localStorage.getItem(STORAGE)||'{}');p.prototypes=p.prototypes||{};p.speakerMean=p.speakerMean||150;return p}catch{return{prototypes:{},speakerMean:150}}}
function savePersonal(){localStorage.setItem(STORAGE,JSON.stringify(personal));updateTrainUI()}
function notice(t,ok=false,ms=2600){const n=$('notice');n.textContent=t;n.hidden=false;n.classList.toggle('ok',ok);if(ms)setTimeout(()=>{if(n.textContent===t)n.hidden=true},ms)}
function status(t,w=false){$('status').innerHTML=t;$('status').classList.toggle('warn',w);if(w)notice($('status').textContent)}
function friendly(e){if(e?.name==='NotAllowedError')return'Microphone permission was denied for this site.';if(e?.name==='NotFoundError')return'No microphone was found.';return e?.message||'HeadAudio could not start.'}
for(const name of names){const label=document.createElement('div');label.className='viseme-name';label.textContent=name;const bar=document.createElement('div');bar.className='viseme-bar';const fill=document.createElement('span');bar.append(fill);$('visemeGrid').append(label,bar);bars[name]={label,fill}}
function makeTrainButton(t,type){const b=document.createElement('button');b.className='train-btn'+(type==='diph'?' diph':'');b.dataset.store=type==='mono'?t.store:t.storeA;b.innerHTML=`<b>${t.word} ${t.ipa}</b><span>${t.hint} → ${type==='mono'?t.v:`${t.start}→${t.end}`}</span>`;b.onclick=()=>type==='mono'?captureMono(t,b):captureDiph(t,b);$(type==='mono'?'monoGrid':'diphGrid').append(b);return b}
mono.forEach(t=>t.button=makeTrainButton(t,'mono'));diph.forEach(t=>t.button=makeTrainButton(t,'diph'));
function updateTrainUI(){let expanded=0;for(const t of mono){const p=personal.prototypes[t.store];t.button.classList.toggle('ready',!!p);t.button.querySelector('span').textContent=p?`trained · ${p.samples} frames · tap to replace → ${t.v}`:`${t.hint} → ${t.v}`;if(p)expanded++}for(const t of diph){const a=personal.prototypes[t.storeA],b=personal.prototypes[t.storeB],ok=!!a&&!!b;t.button.classList.toggle('ready',ok);t.button.querySelector('span').textContent=ok?`trained transition · ${a.samples}+${b.samples} frames · ${t.start}→${t.end}`:`${t.hint} → ${t.start}→${t.end}`;if(ok)expanded+=2}const total=Object.keys(personal.prototypes).length;$('profilePill').textContent=total?`MY VOICE ${total}`:'STOCK';$('trainReadout').textContent=expanded?`${expanded} expanded-vowel prototype${expanded===1?'':'s'} saved. ${total-expanded} earlier personal prototype${total-expanded===1?'':'s'} also retained.`:'No expanded vowel prototypes yet. Earlier personal training, if present, is still retained.'}
updateTrainUI();
async function diagnostics(){let perm='unavailable';try{if(navigator.permissions?.query)perm=(await navigator.permissions.query({name:'microphone'})).state}catch{}$('diag').textContent=[`secure context: ${isSecureContext?'yes':'NO'}`,`site mic permission: ${perm}`,`HeadAudio: ${libError?'FAILED':HeadAudio?'loaded':'loading…'}`,`saved personal prototypes: ${Object.keys(personal.prototypes).length}`,`capture: ${capture?capture.type:'idle'}`,`source: HeadAudio @ ${COMMIT.slice(0,8)}`].join('\n')}
async function ask(){try{const s=await navigator.mediaDevices.getUserMedia({audio:true});s.getTracks().forEach(t=>t.stop());notice('Microphone permission granted.',true)}catch(e){status(friendly(e),true)}diagnostics()}
function setParam(n,v){if(node){const p=node.parameters.get(n);if(p)p.value=+v}}
function syncControls(){for(const [id,s] of [['speakerMean',''],['vadActive',' dB'],['vadInactive',' dB']])$(id+'Out').textContent=$(id).value+s;$('silSensitivityOut').textContent=(+$('silSensitivity').value).toFixed(2);setParam('speakerMeanHz',$('speakerMean').value);setParam('vadGateActiveDb',$('vadActive').value);setParam('vadGateInactiveDb',$('vadInactive').value);setParam('silSensitivity',$('silSensitivity').value)}
$('speakerMean').value=personal.speakerMean||150;['speakerMean','vadActive','vadInactive','silSensitivity'].forEach(id=>$(id).addEventListener('input',()=>{syncControls();if(id==='speakerMean'){personal.speakerMean=+$('speakerMean').value;savePersonal()}}));syncControls();
function applyPrototype(p){if(!node||!p)return;node.port.postMessage({event:'model',model:[{phoneme:p.code,group:p.group,viseme:p.viseme,mu:new Float32Array(p.mu),sigmaInvLower:new Float32Array(p.sigmaInvLower)}]})}
function applySaved(){if(!node){status('Turn the microphone on first.',true);return}for(const p of Object.values(personal.prototypes))applyPrototype(p);notice('All saved personal prototypes applied.',true);status('Personal prototypes layered over HeadAudio’s stock English model.')}
async function toggleMic(){if(mic){stopMic();return}$('micBtn').disabled=true;$('micBtn').textContent='Starting…';try{await libReady;if(!HeadAudio)throw libError||new Error('HeadAudio failed to load');stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});audioCtx=new AudioContext();await audioCtx.resume();await audioCtx.audioWorklet.addModule(WORKLET_URL);node=new HeadAudio(audioCtx,{processorOptions:{vadEventsEnabled:true,featureEventsEnabled:true,visemeEventsEnabled:true},parameterData:{vadMode:1,vadGateActiveDb:+$('vadActive').value,vadGateInactiveDb:+$('vadInactive').value,silMode:1,silCalibrationWindowSec:3,silSensitivity:+$('silSensitivity').value,speakerMeanHz:+$('speakerMean').value}});await node.loadModel(MODEL_URL);node.onvalue=(k,v)=>{if(k in weights)weights[k]=clamp(v,0,1)};node.onvad=o=>{lastVadDb=Number.isFinite(o.db)?o.db:lastVadDb;lastVadActive=!!o.active};node.onviseme=o=>{if(Number.isInteger(o.viseme))activeIndex=o.viseme;lastDistances=Array.isArray(o.distances)?o.distances:null};node.onfeature=o=>{if(capture&&o?.vector?.length===12)capture.records.push({vector:Array.from(o.vector),le:o.le||0,t:o.t||0})};node.onstarted=()=>{$('modePill').textContent='SPEECH'};node.onended=()=>{$('modePill').textContent='MIC'};node.oncalibrated=o=>{$('silenceBtn').disabled=false;$('silenceBtn').textContent='Calibrate 3s of silence';if(o?.error)status(`Silence calibration failed: ${o.error}`,true);else notice('Silence calibration complete.',true)};source=audioCtx.createMediaStreamSource(stream);source.connect(node);mic=true;applySaved();$('micBtn').textContent='Mic off';$('micBtn').classList.add('active');$('modePill').textContent='MIC';notice('Expanded vowel trainer connected.',true);status('Calibrate silence, then train the stable vowels.')}catch(e){console.error(e);status(friendly(e),true);stopMic(false)}finally{$('micBtn').disabled=false;diagnostics()}}
function stopMic(update=true){capture=null;guideRunning=false;mic=false;try{source?.disconnect()}catch{};try{node?.disconnect()}catch{};stream?.getTracks().forEach(t=>t.stop());source=node=stream=null;audioCtx?.close().catch(()=>{});audioCtx=null;for(const k of keys)weights[k]=0;$('micBtn').textContent='Mic on';$('micBtn').classList.remove('active');$('modePill').textContent='IDLE';setButtonsDisabled(false);if(update)status('Microphone stopped.')}
function calibrateSilence(){if(!node){status('Turn the microphone on first.',true);return}$('silenceBtn').disabled=true;$('silenceBtn').textContent='Stay quiet…';status('Stay quiet for HeadAudio’s three-second silence calibration.');node.calibrate()}
function setButtonsDisabled(v,except=null){for(const b of document.querySelectorAll('.train-btn'))if(b!==except)b.disabled=v;$('trainMonosBtn').disabled=v||guideRunning}
async function startCapture(target,button,type,duration){if(!node){status('Turn the microphone on before training.',true);return null}if(capture)return null;const oldVad=node.parameters.get('vadMode').value;capture={target,records:[],button,oldVad,type};button.classList.add('recording');setButtonsDisabled(true,button);status(`Get ready: ${target.hint}`);notice(`Get ready… ${target.word}`,false,0);setParam('vadMode',0);await sleep(600);if(!capture)return null;status(`GO — ${target.hint}`);$('notice').textContent=`GO — ${target.word}`;await sleep(duration);const c=capture;capture=null;setParam('vadMode',oldVad??1);button.classList.remove('recording');if(!guideRunning)setButtonsDisabled(false);$('notice').hidden=true;return c}
function buildPrototype(code,group,viseme,records){if(records.length<14)throw new Error(`Only ${records.length} usable feature frames.`);const vectors=records.map(r=>new Float32Array(r.vector));const q=node.training.computePrototype(code,group,viseme,vectors);return{code,group,viseme,mu:Array.from(q.mu),sigmaInvLower:Array.from(q.sigmaInvLower),samples:vectors.length,speakerMean:+$('speakerMean').value,created:Date.now()}}
function centralFrames(records){const rs=records.filter(r=>Array.isArray(r.vector)&&r.vector.length===12);if(rs.length<18)return rs;const a=Math.floor(rs.length*.18),b=Math.ceil(rs.length*.82);return rs.slice(a,b)}
async function captureMono(t,button=t.button){const c=await startCapture(t,button,'mono',1850);if(!c)return false;try{const keep=centralFrames(c.records);const p=buildPrototype(t.code,t.group,t.viseme,keep);p.name=t.word;p.kind='monophthong';personal.prototypes[t.store]=p;personal.speakerMean=+$('speakerMean').value;savePersonal();applyPrototype(p);notice(`${t.word} ${t.ipa} trained from ${p.samples} central frames.`,true);status(`${t.word} is live as another acoustic route to HeadAudio’s ${t.v} viseme.`);return true}catch(e){console.error(e);status(`${t.word} training failed: ${e.message}`,true);return false}finally{diagnostics()}}
async function captureDiph(t,button=t.button){const c=await startCapture(t,button,'diph',2300);if(!c)return false;try{let rs=c.records.filter(r=>Array.isArray(r.vector)&&r.vector.length===12);const trim=Math.floor(rs.length*.10);rs=rs.slice(trim,Math.max(trim+1,rs.length-trim));const n=rs.length,cut=Math.max(14,Math.floor(n*.38));const first=rs.slice(0,cut),lastPart=rs.slice(Math.max(cut,n-cut));const p1=buildPrototype(t.codeA,t.groupA,t.startViseme,first),p2=buildPrototype(t.codeB,t.groupB,t.endViseme,lastPart);Object.assign(p1,{name:`${t.word}-start`,kind:'diphthong-start'});Object.assign(p2,{name:`${t.word}-end`,kind:'diphthong-end'});personal.prototypes[t.storeA]=p1;personal.prototypes[t.storeB]=p2;savePersonal();applyPrototype(p1);applyPrototype(p2);notice(`${t.word} trained as ${t.start} → ${t.end}.`,true);status(`${t.word} now has separate beginning and ending acoustic prototypes.`);return true}catch(e){console.error(e);status(`${t.word} training failed: ${e.message}`,true);return false}finally{diagnostics()}}
async function trainMonos(){if(!node){status('Turn Mic on first.',true);return}if(guideRunning||capture)return;guideRunning=true;$('trainMonosBtn').disabled=true;for(let i=0;i<mono.length;i++){const t=mono[i];$('monoSeq').textContent=mono.map((x,j)=>j<i?'✓':j===i?`[${x.word}]`:x.word).join(' · ');await captureMono(t,t.button);await sleep(350)}$('monoSeq').textContent='✓ '+mono.map(x=>x.word).join(' · ');guideRunning=false;setButtonsDisabled(false);$('trainMonosBtn').disabled=false;status('Stable-vowel pass complete. Try normal speech before adding the moving vowels.');notice('Stable vowel space trained.',true)}
function clearExpanded(){for(const k of Object.keys(personal.prototypes))if(k.startsWith(PREFIX))delete personal.prototypes[k];savePersonal();notice('Expanded vowel prototypes cleared. Restart Mic to remove already-loaded copies from this session.',true);status('Earlier personal training was preserved; only the expanded vowel set was cleared.')}
const poses={aa:{o:.92,w:.57,r:0},E:{o:.42,w:.77,r:0},I:{o:.24,w:.82,r:0},O:{o:.62,w:.40,r:.88},U:{o:.22,w:.29,r:1},PP:{o:.02,w:.48,r:0},SS:{o:.20,w:.72,r:0},TH:{o:.22,w:.61,r:0},DD:{o:.30,w:.62,r:0},FF:{o:.12,w:.57,r:0},kk:{o:.38,w:.56,r:0},nn:{o:.25,w:.61,r:0},RR:{o:.40,w:.55,r:.15},CH:{o:.24,w:.66,r:.08},sil:{o:.02,w:.5,r:0}};
const mouth=$('mouth'),upper=$('upperLip'),lower=$('lowerLip'),teeth=$('teeth'),tongue=$('tongue'),chin=$('chin');let ms={o:.02,w:.5,r:0};
function renderMouth(){let t={o:0,w:0,r:0},sum=0;for(const n of names){const v=weights[`viseme_${n}`]||0;if(v){sum+=v;const p=poses[n];t.o+=p.o*v;t.w+=p.w*v;t.r+=p.r*v}}if(sum<.001)t={...poses.sil};else{t.o/=sum;t.w/=sum;t.r/=sum}for(const k in ms)ms[k]=lerp(ms[k],t[k],.3);const width=clamp(34+ms.w*44-ms.r*12,22,92),height=clamp(2+ms.o*52,1.5,62),cx=300,cy=392,l=cx-width,r=cx+width,top=cy-height*(.47+.08*ms.r),bot=cy+height*(.60+.05*ms.o);mouth.setAttribute('d',`M ${l} ${cy} Q ${cx} ${top} ${r} ${cy} Q ${cx} ${bot} ${l} ${cy}Z`);upper.setAttribute('d',`M ${l} ${cy} Q ${cx} ${top-1.4} ${r} ${cy}`);lower.setAttribute('d',`M ${l} ${cy} Q ${cx} ${bot+1.5} ${r} ${cy}`);teeth.style.opacity=(activeIndex===6||activeIndex===9)?.6:0;tongue.style.opacity=(activeIndex===7||activeIndex===11)?.6:0;chin.style.transform=`translateY(${Math.min(15,ms.o*13)}px)`}
function updateStats(){const active=names[clamp(activeIndex,0,14)]||'sil';$('activeViseme').textContent=active;$('shapePill').textContent=active.toUpperCase();$('vadDb').textContent=Number.isFinite(lastVadDb)?`${lastVadDb.toFixed(1)} dB`:'— dB';$('vadState').textContent=lastVadActive?'active':'inactive';$('meterFill').style.width=`${clamp((lastVadDb+70)/45*100,0,100)}%`;let gap=null;if(lastDistances?.length>1){const s=lastDistances.filter(Number.isFinite).slice().sort((a,b)=>a-b);if(s.length>1)gap=s[1]-s[0]}$('confidence').textContent=gap==null?'—':gap.toFixed(1);for(const n of names){const v=weights[`viseme_${n}`]||0;bars[n].fill.style.width=`${v*100}%`;bars[n].label.classList.toggle('active',n===active)}}
function tick(t){const dt=Math.min(50,t-last);last=t;if(node)node.update(dt);renderMouth();updateStats();requestAnimationFrame(tick)}
$('permissionBtn').onclick=ask;$('permissionDiagBtn').onclick=ask;$('micBtn').onclick=toggleMic;$('silenceBtn').onclick=calibrateSilence;$('diagBtn').onclick=diagnostics;$('applySavedBtn').onclick=applySaved;$('clearVowelsBtn').onclick=clearExpanded;$('trainMonosBtn').onclick=trainMonos;const aside=$('controls'),scrim=$('scrim');function drawer(on){aside.classList.toggle('open',on);scrim.classList.toggle('show',on)}$('drawerBtn').onclick=()=>drawer(!aside.classList.contains('open'));scrim.onclick=()=>drawer(false);
diagnostics();libReady.finally(diagnostics);requestAnimationFrame(tick);
