const COMMIT='d3af5f9ff86ab6b2b1913d411a4e1922ec101953';
const BASE=`https://cdn.jsdelivr.net/gh/met4citizen/HeadAudio@${COMMIT}`;
const MODULE_URL=`${BASE}/dist/headaudio.min.mjs`,WORKLET_URL=`${BASE}/dist/headworklet.min.mjs`,MODEL_URL=`${BASE}/dist/model-en-mixed.bin`;
const PERSONAL_STORAGE='voice-face-headaudio-personal-v1';
const TEMP_STORAGE='voice-face-headaudio-temporal-v1';
const $=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,sleep=ms=>new Promise(r=>setTimeout(r,ms));
const names=['aa','E','I','O','U','PP','SS','TH','DD','FF','kk','nn','RR','CH','sil'];
const keys=names.map(v=>`viseme_${v}`),rawWeights=Object.fromEntries(keys.map(k=>[k,0])),finalWeights=Object.fromEntries(keys.map(k=>[k,0])),bars={};
const targets=[
 {key:'pb',label:'P / B',prompt:'pa ba pa ba pa ba',viseme:'PP',hint:'Crisp lip closure and release.'},
 {key:'m',label:'M',prompt:'ma ma ma ma ma',viseme:'PP',hint:'Clear closed-lip onset, then vowel.'},
 {key:'td',label:'T / D',prompt:'ta da ta da ta da',viseme:'DD',hint:'Natural tongue-tip stop.'},
 {key:'kg',label:'K / G',prompt:'ka ga ka ga ka ga',viseme:'kk',hint:'Natural rear stop.'},
 {key:'chj',label:'CH / J',prompt:'cha ja cha ja cha ja',viseme:'CH',hint:'Short affricate attack.'}
].map(x=>({...x,visemeIndex:names.indexOf(x.viseme)}));
let HeadAudio=null,libError=null,audioCtx=null,stream=null,source=null,node=null,mic=false;
let personal=loadJSON(PERSONAL_STORAGE,{prototypes:{},speakerMean:150});
let temporal=loadJSON(TEMP_STORAGE,{templates:{}}); temporal.templates=temporal.templates||{};
let featureHistory=[],capture=null,lastVadDb=-100,lastVadActive=false,rawActive=14,override=null,lastTriggerAt=-Infinity,lastScore=null,last=performance.now();
const libReady=import(MODULE_URL).then(m=>HeadAudio=m.HeadAudio).catch(e=>{libError=e;console.error(e)});
function loadJSON(k,f){try{return Object.assign({},f,JSON.parse(localStorage.getItem(k)||'{}'))}catch{return structuredClone(f)}}
function saveTemporal(){localStorage.setItem(TEMP_STORAGE,JSON.stringify(temporal));updateTrainUI()}
function notice(t,ok=false,ms=2600){const n=$('notice');n.textContent=t;n.hidden=false;n.classList.toggle('ok',ok);if(ms)setTimeout(()=>{if(n.textContent===t)n.hidden=true},ms)}
function status(t,w=false){$('status').innerHTML=t;$('status').classList.toggle('warn',w);if(w)notice($('status').textContent)}
function friendly(e){if(e?.name==='NotAllowedError')return'Microphone permission was denied for this site.';if(e?.name==='NotFoundError')return'No microphone was found.';return e?.message||'HeadAudio could not start.'}
for(const n of names){const l=document.createElement('div');l.className='viseme-name';l.textContent=n;const b=document.createElement('div');b.className='viseme-bar';const f=document.createElement('span');b.append(f);$('visemeGrid').append(l,b);bars[n]={label:l,fill:f}}
for(const t of targets){const b=document.createElement('button');b.className='train-btn';b.dataset.key=t.key;b.innerHTML=`<b>${t.label}</b><span>${t.prompt} · ${t.hint}</span>`;b.onclick=()=>beginTransientCapture(t,b);$('trainGrid').append(b);t.button=b}
function updateTrainUI(){let n=0;const parts=[];for(const t of targets){const q=temporal.templates[t.key];t.button.classList.toggle('ready',!!q);if(q){n++;t.button.querySelector('span').textContent=`trained · ${q.events} onsets · threshold ${q.threshold.toFixed(2)} · tap to replace`;parts.push(`${t.label}:${q.events}`)}else t.button.querySelector('span').textContent=`${t.prompt} · ${t.hint}`} $('trainReadout').textContent=n?`${n} temporal template${n===1?'':'s'} saved locally · ${parts.join(' · ')}`:'No temporal templates yet.'}
updateTrainUI();
async function diagnostics(){let perm='unavailable';try{if(navigator.permissions?.query)perm=(await navigator.permissions.query({name:'microphone'})).state}catch{}$('diag').textContent=[`secure context: ${isSecureContext?'yes':'NO'}`,`site mic permission: ${perm}`,`HeadAudio: ${libError?'FAILED':HeadAudio?'loaded':'loading…'}`,`personal Gaussian prototypes: ${Object.keys(personal.prototypes||{}).length}`,`temporal templates: ${Object.keys(temporal.templates||{}).length}`,`feature history: ${featureHistory.length}`,`capture: ${capture?capture.target.label:'idle'}`,`source: HeadAudio @ ${COMMIT.slice(0,8)}`].join('\n')}
async function ask(){try{const s=await navigator.mediaDevices.getUserMedia({audio:true});s.getTracks().forEach(t=>t.stop());notice('Microphone permission granted.',true)}catch(e){status(friendly(e),true)}diagnostics()}
function setParam(n,v){if(node){const p=node.parameters.get(n);if(p)p.value=+v}}
function syncControls(){for(const [id,s] of [['speakerMean',''],['vadActive',' dB'],['vadInactive',' dB']])$(id+'Out').textContent=$(id).value+s;$('silSensitivityOut').textContent=(+$('silSensitivity').value).toFixed(2);$('temporalSensitivityOut').textContent=(+$('temporalSensitivity').value).toFixed(2);$('temporalHoldOut').textContent=`${$('temporalHold').value} ms`;setParam('speakerMeanHz',$('speakerMean').value);setParam('vadGateActiveDb',$('vadActive').value);setParam('vadGateInactiveDb',$('vadInactive').value);setParam('silSensitivity',$('silSensitivity').value)}
$('speakerMean').value=personal.speakerMean||150;['speakerMean','vadActive','vadInactive','silSensitivity','temporalSensitivity','temporalHold'].forEach(id=>$(id).addEventListener('input',syncControls));syncControls();
function applyPrototype(p){if(!node||!p)return;node.port.postMessage({event:'model',model:[{phoneme:p.code||p.name?.slice(0,2)||'x',group:p.group,viseme:p.viseme,mu:new Float32Array(p.mu),sigmaInvLower:new Float32Array(p.sigmaInvLower)}]})}
function applyPersonal(){if(!node)return;for(const p of Object.values(personal.prototypes||{}))applyPrototype(p)}
async function toggleMic(){if(mic){stopMic();return}$('micBtn').disabled=true;$('micBtn').textContent='Starting…';try{await libReady;if(!HeadAudio)throw libError||new Error('HeadAudio failed to load');stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});audioCtx=new AudioContext();await audioCtx.resume();await audioCtx.audioWorklet.addModule(WORKLET_URL);node=new HeadAudio(audioCtx,{processorOptions:{vadEventsEnabled:true,featureEventsEnabled:true,visemeEventsEnabled:true},parameterData:{vadMode:1,vadGateActiveDb:+$('vadActive').value,vadGateInactiveDb:+$('vadInactive').value,silMode:1,silCalibrationWindowSec:3,silSensitivity:+$('silSensitivity').value,speakerMeanHz:+$('speakerMean').value}});await node.loadModel(MODEL_URL);node.onvalue=(k,v)=>{if(k in rawWeights)rawWeights[k]=clamp(v,0,1)};node.onvad=o=>{lastVadDb=Number.isFinite(o.db)?o.db:lastVadDb;lastVadActive=!!o.active};node.onviseme=o=>{if(Number.isInteger(o.viseme))rawActive=o.viseme};node.onfeature=onFeature;node.onstarted=()=>{$('modePill').textContent='SPEECH'};node.onended=()=>{$('modePill').textContent='MIC'};node.oncalibrated=o=>{$('silenceBtn').disabled=false;$('silenceBtn').textContent='Calibrate 3s of silence';if(o?.error)status(`Silence calibration failed: ${o.error}`,true);else notice('Silence calibration complete.',true)};source=audioCtx.createMediaStreamSource(stream);source.connect(node);applyPersonal();mic=true;$('micBtn').textContent='Mic off';$('micBtn').classList.add('active');$('modePill').textContent='MIC';status(`Temporal HeadAudio is live. ${Object.keys(personal.prototypes||{}).length} saved Gaussian prototypes and ${Object.keys(temporal.templates||{}).length} transient templates loaded.`);notice('Temporal model connected.',true)}catch(e){console.error(e);status(friendly(e),true);stopMic(false)}finally{$('micBtn').disabled=false;diagnostics()}}
function stopMic(update=true){if(capture)finishTransientCapture(false);mic=false;try{source?.disconnect()}catch{};try{node?.disconnect()}catch{};stream?.getTracks().forEach(t=>t.stop());source=node=stream=null;audioCtx?.close().catch(()=>{});audioCtx=null;featureHistory=[];override=null;for(const k of keys)rawWeights[k]=finalWeights[k]=0;$('micBtn').textContent='Mic on';$('micBtn').classList.remove('active');$('modePill').textContent='IDLE';if(update)status('Microphone stopped.')}
function calibrateSilence(){if(!node){status('Turn the microphone on first.',true);return}$('silenceBtn').disabled=true;$('silenceBtn').textContent='Stay quiet…';status('Stay quiet for HeadAudio’s three-second silence calibration.');node.calibrate()}
function onFeature(o){if(!o?.vector||o.vector.length!==12)return;const rec={v:Array.from(o.vector),db:10*(o.le||-10),t:performance.now()};featureHistory.push(rec);if(featureHistory.length>80)featureHistory.splice(0,featureHistory.length-80);if(capture)capture.records.push(rec);else evaluateTemporal()}
function meanVec(records,a,b){const out=new Array(12).fill(0);let n=0;for(let i=Math.max(0,a);i<Math.min(records.length,b);i++){const v=records[i].v;for(let j=0;j<12;j++)out[j]+=v[j];n++}if(!n)return null;for(let j=0;j<12;j++)out[j]/=n;return out}
function meanDb(records,a,b){let s=0,n=0;for(let i=Math.max(0,a);i<Math.min(records.length,b);i++){s+=records[i].db;n++}return n?s/n:-100}
function descriptor(records,i){if(i<4||i+3>=records.length)return null;const pre=meanVec(records,i-3,i),attack=meanVec(records,i,i+2),after=meanVec(records,i+2,i+4);if(!pre||!attack||!after)return null;const pDb=meanDb(records,i-3,i),aDb=meanDb(records,i,i+2),zDb=meanDb(records,i+2,i+4),floor=meanDb(records,Math.max(0,i-10),Math.max(1,i-5));return [...pre,...attack,...after,(aDb-pDb)/20,(zDb-aDb)/20,(zDb-pDb)/20,(Math.max(aDb,zDb)-floor)/40]}
function detectOnsets(records,maxN=8){if(records.length<12)return[];const c=[];for(let i=5;i<records.length-4;i++){const db=records[i].db,base=Math.min(...records.slice(i-4,i).map(x=>x.db)),rise=db-base;if(db>-55&&rise>2.3){const prev=records[i-1].db-(Math.min(...records.slice(i-5,i-1).map(x=>x.db)));const next=records[i+1].db-(Math.min(...records.slice(i-3,i+1).map(x=>x.db)));if(rise>=prev&&rise>=next)c.push({i,score:rise})}}c.sort((a,b)=>b.score-a.score);const chosen=[];for(const x of c){if(chosen.every(y=>Math.abs(y.i-x.i)>16))chosen.push(x);if(chosen.length>=maxN)break}return chosen.sort((a,b)=>a.i-b.i).map(x=>x.i)}
function distDesc(x,m,v){let s=0,n=0;for(let i=0;i<x.length;i++){const z=x[i]-m[i],den=Math.max(v[i],i<36?.012:.02);s+=z*z/den;n++}return s/n}
async function beginTransientCapture(t,b){if(!node){status('Turn the microphone on before training.',true);return}if(capture)return;capture={target:t,button:b,records:[],oldVad:node.parameters.get('vadMode').value};b.classList.add('recording');for(const q of document.querySelectorAll('.train-btn'))q.disabled=true;setParam('vadMode',0);notice(`Get ready… ${t.prompt}`,false,0);status(`Get ready, then say: ${t.prompt}`);await sleep(650);if(!capture)return;$('notice').textContent=`GO — ${t.prompt}`;status(`GO — ${t.prompt}`);setTimeout(()=>finishTransientCapture(true),4700)}
function finishTransientCapture(commit){if(!capture)return;const c=capture;capture=null;setParam('vadMode',c.oldVad??1);c.button.classList.remove('recording');for(const q of document.querySelectorAll('.train-btn'))q.disabled=false;$('notice').hidden=true;if(!commit)return;const onset=detectOnsets(c.records,8),descs=onset.map(i=>descriptor(c.records,i)).filter(Boolean);if(descs.length<4){status(`I only found ${descs.length} clear ${c.target.label} onsets. Try again with slightly cleaner gaps between syllables.`,true);return}const D=descs[0].length,mean=new Array(D).fill(0),variance=new Array(D).fill(0);for(const d of descs)for(let j=0;j<D;j++)mean[j]+=d[j]/descs.length;for(const d of descs)for(let j=0;j<D;j++){const z=d[j]-mean[j];variance[j]+=z*z/Math.max(1,descs.length-1)}const self=descs.map(d=>distDesc(d,mean,variance)),avg=self.reduce((a,b)=>a+b,0)/self.length,sd=Math.sqrt(self.reduce((a,b)=>a+(b-avg)**2,0)/Math.max(1,self.length-1));const threshold=Math.max(1.15,avg+2.5*sd,Math.max(...self)*1.25);temporal.templates[c.target.key]={key:c.target.key,label:c.target.label,visemeIndex:c.target.visemeIndex,mean,variance,threshold,events:descs.length,created:Date.now()};saveTemporal();notice(`${c.target.label} temporal template trained from ${descs.length} attacks.`,true);status(`${c.target.label} is live. Try ordinary words containing that sound and watch the TEMP indicator.`);diagnostics()}
function evaluateTemporal(){if(!$('temporalEnabled').checked||capture||featureHistory.length<12||!Object.keys(temporal.templates).length)return;const i=featureHistory.length-4;if(i<5)return;const r=featureHistory,db=r[i].db,base=Math.min(...r.slice(Math.max(0,i-4),i).map(x=>x.db)),rise=db-base;if(db<-57||rise<1.8)return;const now=performance.now();if(now-lastTriggerAt<110)return;const d=descriptor(r,i);if(!d)return;let best=null;for(const q of Object.values(temporal.templates)){const score=distDesc(d,q.mean,q.variance),ratio=score/(q.threshold*(+$('temporalSensitivity').value));if(!best||ratio<best.ratio)best={q,score,ratio}}lastScore=best;if(best&&best.ratio<=1){lastTriggerAt=now;override={visemeIndex:best.q.visemeIndex,label:best.q.label,until:now+(+$('temporalHold').value),score:best.score,ratio:best.ratio};$('temporalPill').textContent=`TEMP ${best.q.label}`;$('temporalPill').classList.add('active')}}
function clearTemporal(){temporal={templates:{}};localStorage.removeItem(TEMP_STORAGE);updateTrainUI();override=null;notice('Temporal templates cleared.',true);status('Temporal layer cleared; base personal HeadAudio remains untouched.')}
const poses={aa:{o:.92,w:.57,r:0},E:{o:.42,w:.77,r:0},I:{o:.24,w:.82,r:0},O:{o:.62,w:.40,r:.88},U:{o:.22,w:.29,r:1},PP:{o:.02,w:.48,r:0},SS:{o:.20,w:.72,r:0},TH:{o:.22,w:.61,r:0},DD:{o:.30,w:.62,r:0},FF:{o:.12,w:.57,r:0},kk:{o:.38,w:.56,r:0},nn:{o:.25,w:.61,r:0},RR:{o:.40,w:.55,r:.15},CH:{o:.24,w:.66,r:.08},sil:{o:.02,w:.5,r:0}};
const mouth=$('mouth'),upper=$('upperLip'),lower=$('lowerLip'),teeth=$('teeth'),tongue=$('tongue'),chin=$('chin');let ms={o:.02,w:.5,r:0};
function composeFinal(now){for(const k of keys)finalWeights[k]=rawWeights[k]||0;let finalIndex=rawActive;if(override&&now<override.until&&$('temporalEnabled').checked){const n=names[override.visemeIndex];for(const k of keys)finalWeights[k]*=.22;finalWeights[`viseme_${n}`]=1;finalIndex=override.visemeIndex}else if(override){override=null;$('temporalPill').textContent='TEMP —';$('temporalPill').classList.remove('active')}window.LipSyncOutput={viseme:names[finalIndex]||'sil',visemeIndex:finalIndex,weights:{...finalWeights},temporal:override?{label:override.label,ratio:override.ratio}:null};return finalIndex}
function renderMouth(finalIndex){let t={o:0,w:0,r:0},sum=0;for(const n of names){const v=finalWeights[`viseme_${n}`]||0;if(v){sum+=v;const p=poses[n];t.o+=p.o*v;t.w+=p.w*v;t.r+=p.r*v}}if(sum<.001)t={...poses.sil};else{t.o/=sum;t.w/=sum;t.r/=sum}for(const k in ms)ms[k]=lerp(ms[k],t[k],.32);const width=clamp(34+ms.w*44-ms.r*12,22,92),height=clamp(2+ms.o*52,1.5,62),cx=300,cy=392,l=cx-width,r=cx+width,top=cy-height*(.47+.08*ms.r),bot=cy+height*(.60+.05*ms.o);mouth.setAttribute('d',`M ${l} ${cy} Q ${cx} ${top} ${r} ${cy} Q ${cx} ${bot} ${l} ${cy}Z`);upper.setAttribute('d',`M ${l} ${cy} Q ${cx} ${top-1.4} ${r} ${cy}`);lower.setAttribute('d',`M ${l} ${cy} Q ${cx} ${bot+1.5} ${r} ${cy}`);teeth.style.opacity=(finalIndex===6||finalIndex===9)?.6:0;tongue.style.opacity=(finalIndex===7||finalIndex===11)?.6:0;chin.style.transform=`translateY(${Math.min(15,ms.o*13)}px)`}
function updateStats(finalIndex){$('rawPrediction').textContent=names[rawActive]||'sil';$('finalPrediction').textContent=names[finalIndex]||'sil';$('shapePill').textContent=(names[finalIndex]||'sil').toUpperCase();$('meterFill').style.width=`${clamp((lastVadDb+70)/45*100,0,100)}%`;$('matchScore').textContent=lastScore?`${lastScore.ratio.toFixed(2)}×`:'—';for(const n of names){const v=finalWeights[`viseme_${n}`]||0;bars[n].fill.style.width=`${v*100}%`;bars[n].label.classList.toggle('active',n===names[finalIndex])}}
function tick(t){const dt=Math.min(50,t-last);last=t;if(node)node.update(dt);const f=composeFinal(t);renderMouth(f);updateStats(f);requestAnimationFrame(tick)}
$('permissionBtn').onclick=ask;$('permissionDiagBtn').onclick=ask;$('micBtn').onclick=toggleMic;$('silenceBtn').onclick=calibrateSilence;$('diagBtn').onclick=diagnostics;$('clearTemporalBtn').onclick=clearTemporal;$('testTemporalBtn').onclick=()=>{override={visemeIndex:5,label:'P/B TEST',until:performance.now()+350,score:0,ratio:0};notice('Temporal override test: PP',true)};const aside=$('controls'),scrim=$('scrim');function drawer(on){aside.classList.toggle('open',on);scrim.classList.toggle('show',on)}$('drawerBtn').onclick=()=>drawer(!aside.classList.contains('open'));scrim.onclick=()=>drawer(false);
diagnostics();libReady.finally(diagnostics);requestAnimationFrame(tick);
