const card=(label,weights={})=>({label,weights});
const tier=(subtle,expressive,extreme)=>({subtle,expressive,extreme});
const FAMILIES={
  attentive:{
    brows:tier([card('quiet inner lift',{browInnerUp_L:.18,browInnerUp_R:.18}),card('left brow leads',{browInnerUp_L:.22,browOuterUp_R:.10})],[card('intent brow lift',{browInnerUp_L:.34,browInnerUp_R:.30,browOuterUp_L:.20,browOuterUp_R:.18}),card('questioning attention',{browOuterUp_L:.40,browInnerUp_R:.28})],[card('riveted attention',{browInnerUp_L:.58,browInnerUp_R:.58,browOuterUp_L:.42,browOuterUp_R:.42}),card('urgent focus',{browDown_L:.38,browDown_R:.38,browInnerUp_L:.30,browInnerUp_R:.30})]),
    eyes:tier([card('soft focus',{eyeSquint_L:.09,eyeSquint_R:.09}),card('eyes open slightly',{eyeWide_L:.14,eyeWide_R:.14})],[card('keen focus',{eyeWide_L:.28,eyeWide_R:.28}),card('one eye considers',{eyeSquint_L:.30,eyeSquint_R:.09})],[card('unbroken stare',{eyeWide_L:.56,eyeWide_R:.56}),card('laser focus',{eyeSquint_L:.48,eyeSquint_R:.42,cheekRaiser_L:.18,cheekRaiser_R:.18})]),
    mouth:tier([card('lips gather',{mouthPress_L:.10,mouthPress_R:.10}),card('almost a smile',{mouthSmile_L:.10,mouthSmile_R:.07})],[card('engaged half-smile',{mouthSmile_L:.28,mouthSmile_R:.18,mouthDimple_L:.16}),card('thought held',{mouthPress_L:.32,mouthPress_R:.32,mouthShrugUpper:.12})],[card('eager recognition',{mouthSmile_L:.52,mouthSmile_R:.45,mouthStretch_L:.20,mouthStretch_R:.20}),card('breathless attention',{mouthLowerDown_L:.34,mouthLowerDown_R:.34,mouthUpperUp_L:.18,mouthUpperUp_R:.18})])},
  warm:{
    brows:tier([card('open brows',{browOuterUp_L:.13,browOuterUp_R:.13}),card('friendly inner lift',{browInnerUp_L:.12,browInnerUp_R:.12})],[card('bright brows',{browOuterUp_L:.30,browOuterUp_R:.30,browInnerUp_L:.20,browInnerUp_R:.20}),card('delighted recognition',{browOuterUp_L:.38,browOuterUp_R:.32})],[card('joy breaks through',{browOuterUp_L:.60,browOuterUp_R:.60,browInnerUp_L:.38,browInnerUp_R:.38}),card('laughing brows',{browInnerUp_L:.50,browInnerUp_R:.50})]),
    eyes:tier([card('cheeks rise',{cheekRaiser_L:.18,cheekRaiser_R:.18}),card('smiling squint',{eyeSquint_L:.16,eyeSquint_R:.16})],[card('happy eyes',{cheekRaiser_L:.42,cheekRaiser_R:.42,eyeSquint_L:.34,eyeSquint_R:.34}),card('crooked delight',{cheekRaiser_L:.48,cheekRaiser_R:.28,eyeSquint_L:.38,eyeSquint_R:.20})],[card('eyes crinkle with joy',{cheekRaiser_L:.78,cheekRaiser_R:.78,eyeSquint_L:.66,eyeSquint_R:.66}),card('helpless laughter',{cheekRaiser_L:.90,cheekRaiser_R:.82,eyeSquint_L:.78,eyeSquint_R:.70})]),
    mouth:tier([card('balanced smile',{mouthSmile_L:.34,mouthSmile_R:.34}),card('crooked smile',{mouthSmile_L:.40,mouthSmile_R:.20})],[card('open happiness',{mouthSmile_L:.64,mouthSmile_R:.64,mouthDimple_L:.30,mouthDimple_R:.30}),card('broad crooked grin',{mouthSmile_L:.74,mouthSmile_R:.48,mouthStretch_L:.22,mouthStretch_R:.16})],[card('unmistakable delight',{mouthSmile_L:.96,mouthSmile_R:.96,mouthDimple_L:.58,mouthDimple_R:.58,mouthStretch_L:.34,mouthStretch_R:.34}),card('huge asymmetric grin',{mouthSmile_L:1,mouthSmile_R:.72,mouthDimple_L:.66,mouthDimple_R:.34,mouthUpperUp_L:.24,mouthUpperUp_R:.20})])},
  sceptical:{
    brows:tier([card('left brow challenges',{browDown_L:.34,browInnerUp_R:.24}),card('right brow challenges',{browDown_R:.34,browInnerUp_L:.24})],[card('open disbelief',{browDown_L:.52,browOuterUp_R:.46}),card('brows reject',{browDown_L:.46,browDown_R:.46})],[card('furious disbelief',{browDown_L:.82,browOuterUp_R:.68,browInnerUp_R:.40}),card('absolute refusal',{browDown_L:.78,browDown_R:.78})]),
    eyes:tier([card('left eye narrows',{eyeSquint_L:.27,eyeSquint_R:.08}),card('measured squint',{eyeSquint_L:.18,eyeSquint_R:.18})],[card('incredulous squint',{eyeSquint_L:.48,eyeSquint_R:.34,cheekRaiser_L:.20,cheekRaiser_R:.14}),card('hard side-eye',{eyeSquint_L:.58,eyeSquint_R:.14})],[card('withering glare',{eyeSquint_L:.82,eyeSquint_R:.58,cheekRaiser_L:.38,cheekRaiser_R:.28}),card('can you be serious',{eyeWide_L:.54,eyeSquint_R:.68})]),
    mouth:tier([card('one-sided press',{mouthPress_L:.25,mouthPress_R:.10}),card('doubtful corner',{mouthFrown_R:.20,mouthPress_L:.10})],[card('frustrated press',{mouthPress_L:.54,mouthPress_R:.54,mouthFrown_L:.26,mouthFrown_R:.26}),card('disbelieving twist',{mouthStretch_L:.52,mouthPress_R:.36,mouthFrown_R:.30})],[card('barely contained frustration',{mouthPress_L:.88,mouthPress_R:.88,mouthFrown_L:.52,mouthFrown_R:.52,mouthStretch_L:.24,mouthStretch_R:.24}),card('exasperated grimace',{mouthStretch_L:.72,mouthStretch_R:.72,mouthLowerDown_L:.34,mouthLowerDown_R:.34,mouthPress_L:.40,mouthPress_R:.40})])},
  concerned:{
    brows:tier([card('inner brows rise',{browInnerUp_L:.45,browInnerUp_R:.45}),card('uneven worry',{browInnerUp_L:.48,browInnerUp_R:.30})],[card('plain worry',{browInnerUp_L:.64,browInnerUp_R:.64,browDown_L:.18,browDown_R:.18}),card('fear begins',{browInnerUp_L:.72,browInnerUp_R:.58,browOuterUp_L:.25,browOuterUp_R:.25})],[card('fearful arch',{browInnerUp_L:.96,browInnerUp_R:.96,browOuterUp_L:.62,browOuterUp_R:.62}),card('anguished brows',{browInnerUp_L:1,browInnerUp_R:1,browDown_L:.38,browDown_R:.38})]),
    eyes:tier([card('eyes search',{eyeWide_L:.19,eyeWide_R:.19}),card('painful squint',{eyeSquint_L:.15,eyeSquint_R:.15})],[card('worried stare',{eyeWide_L:.46,eyeWide_R:.46}),card('uneven alarm',{eyeWide_L:.58,eyeWide_R:.34})],[card('eyes full of fear',{eyeWide_L:.92,eyeWide_R:.92}),card('flinching fear',{eyeWide_L:.56,eyeWide_R:.56,eyeSquint_L:.28,eyeSquint_R:.28})]),
    mouth:tier([card('corners fall',{mouthFrown_L:.23,mouthFrown_R:.23}),card('lower lip worries',{mouthShrugLower:.18})],[card('visible distress',{mouthFrown_L:.52,mouthFrown_R:.52,mouthShrugLower:.34}),card('anxious mouth',{mouthLowerDown_L:.38,mouthLowerDown_R:.38,mouthStretch_L:.22,mouthStretch_R:.22})],[card('anguished mouth',{mouthFrown_L:.88,mouthFrown_R:.88,mouthShrugLower:.60,mouthLowerDown_L:.46,mouthLowerDown_R:.46}),card('silent gasp',{mouthLowerDown_L:.78,mouthLowerDown_R:.78,mouthUpperUp_L:.32,mouthUpperUp_R:.32,mouthStretch_L:.40,mouthStretch_R:.40})])},
  guarded:{
    brows:tier([card('brows settle',{browDown_L:.16,browDown_R:.16}),card('one brow locks',{browDown_L:.20,browDown_R:.10})],[card('anger gathers',{browDown_L:.52,browDown_R:.52}),card('uneven irritation',{browDown_L:.62,browDown_R:.40,browInnerUp_R:.12})],[card('furious brow',{browDown_L:.96,browDown_R:.96}),card('explosive anger',{browDown_L:1,browDown_R:1,browInnerUp_L:.24,browInnerUp_R:.24})]),
    eyes:tier([card('eyes narrow',{eyeSquint_L:.14,eyeSquint_R:.14}),card('side tension',{eyeSquint_L:.18,eyeSquint_R:.08})],[card('angry glare',{eyeSquint_L:.46,eyeSquint_R:.46,cheekRaiser_L:.18,cheekRaiser_R:.18}),card('one-eyed warning',{eyeSquint_L:.60,eyeSquint_R:.30})],[card('murderous glare',{eyeSquint_L:.82,eyeSquint_R:.82,cheekRaiser_L:.42,cheekRaiser_R:.42}),card('rage stare',{eyeWide_L:.44,eyeWide_R:.44,eyeSquint_L:.26,eyeSquint_R:.26})]),
    mouth:tier([card('lips seal',{mouthPress_L:.27,mouthPress_R:.27}),card('one side locks',{mouthPress_L:.29,mouthPress_R:.13})],[card('clenched anger',{mouthPress_L:.66,mouthPress_R:.66,mouthStretch_L:.20,mouthStretch_R:.20}),card('hostile sneer',{noseSneer_L:.42,noseSneer_R:.30,mouthUpperUp_L:.32,mouthUpperUp_R:.24,mouthFrown_L:.28,mouthFrown_R:.28})],[card('white-knuckle restraint',{mouthPress_L:1,mouthPress_R:1,mouthStretch_L:.48,mouthStretch_R:.48,mouthFrown_L:.38,mouthFrown_R:.38}),card('snarling fury',{noseSneer_L:.88,noseSneer_R:.88,mouthUpperUp_L:.74,mouthUpperUp_R:.74,mouthFrown_L:.54,mouthFrown_R:.54,mouthStretch_L:.40,mouthStretch_R:.40})])},
  activated:{
    brows:tier([card('brows spring open',{browInnerUp_L:.38,browInnerUp_R:.38,browOuterUp_L:.28,browOuterUp_R:.28}),card('sharp outer lift',{browOuterUp_L:.38,browOuterUp_R:.38})],[card('startled brows',{browInnerUp_L:.66,browInnerUp_R:.66,browOuterUp_L:.58,browOuterUp_R:.58}),card('shock arrives unevenly',{browOuterUp_L:.76,browInnerUp_R:.58})],[card('total shock',{browInnerUp_L:1,browInnerUp_R:1,browOuterUp_L:1,browOuterUp_R:1}),card('alarm peak',{browInnerUp_L:.88,browInnerUp_R:.88,browOuterUp_L:.92,browOuterUp_R:.92})]),
    eyes:tier([card('eyes widen',{eyeWide_L:.50,eyeWide_R:.50}),card('uneven startle',{eyeWide_L:.55,eyeWide_R:.35})],[card('startled eyes',{eyeWide_L:.76,eyeWide_R:.76}),card('one eye catches up',{eyeWide_L:.84,eyeWide_R:.58})],[card('eyes at maximum',{eyeWide_L:1,eyeWide_R:1}),card('full-body shock',{eyeWide_L:.96,eyeWide_R:.90,cheekRaiser_L:.24,cheekRaiser_R:.24})]),
    mouth:tier([card('mouth stretches',{mouthStretch_L:.25,mouthStretch_R:.25}),card('lower lip drops',{mouthLowerDown_L:.20,mouthLowerDown_R:.20})],[card('visible gasp',{mouthLowerDown_L:.52,mouthLowerDown_R:.52,mouthUpperUp_L:.28,mouthUpperUp_R:.28,mouthStretch_L:.26,mouthStretch_R:.26}),card('shock held in',{mouthPress_L:.48,mouthPress_R:.48,mouthShrugUpper:.30})],[card('silent scream',{mouthLowerDown_L:.92,mouthLowerDown_R:.92,mouthUpperUp_L:.62,mouthUpperUp_R:.62,mouthStretch_L:.58,mouthStretch_R:.58}),card('stunned open mouth',{mouthLowerDown_L:.82,mouthLowerDown_R:.82,mouthFrown_L:.44,mouthFrown_R:.44,mouthStretch_L:.40,mouthStretch_R:.40})])},
  disgusted:{
    brows:tier([card('faint distaste',{browDown_L:.18,browDown_R:.14}),card('one brow recoils',{browDown_L:.25,browOuterUp_R:.16})],[card('disapproving brow',{browDown_L:.48,browDown_R:.38,browOuterUp_R:.22}),card('repelled brows',{browDown_L:.55,browDown_R:.55})],[card('visceral rejection',{browDown_L:.86,browDown_R:.86,browInnerUp_L:.22,browInnerUp_R:.22}),card('revolted disbelief',{browDown_L:.72,browOuterUp_R:.64})]),
    eyes:tier([card('nose notices',{noseSneer_L:.20,noseSneer_R:.20,eyeSquint_L:.08,eyeSquint_R:.08}),card('uneven recoil',{noseSneer_L:.26,noseSneer_R:.12})],[card('clear revulsion',{noseSneer_L:.58,noseSneer_R:.58,eyeSquint_L:.32,eyeSquint_R:.32}),card('one-sided disgust',{noseSneer_L:.68,noseSneer_R:.30,eyeSquint_L:.46,eyeSquint_R:.18})],[card('full nose wrinkle',{noseSneer_L:1,noseSneer_R:1,eyeSquint_L:.64,eyeSquint_R:.64,cheekRaiser_L:.36,cheekRaiser_R:.36}),card('flinching revulsion',{noseSneer_L:.92,noseSneer_R:.82,eyeSquint_L:.78,eyeSquint_R:.58})]),
    mouth:tier([card('upper lip objects',{mouthUpperUp_L:.22,mouthUpperUp_R:.18,mouthFrown_L:.12,mouthFrown_R:.12}),card('distasteful twist',{mouthUpperUp_L:.28,mouthPress_R:.18})],[card('repelled lip curl',{mouthUpperUp_L:.58,mouthUpperUp_R:.58,mouthFrown_L:.34,mouthFrown_R:.34}),card('asymmetric revulsion',{mouthUpperUp_L:.70,mouthUpperUp_R:.32,mouthStretch_L:.28,mouthFrown_R:.36})],[card('unmistakable disgust',{mouthUpperUp_L:1,mouthUpperUp_R:1,mouthFrown_L:.66,mouthFrown_R:.66,mouthLowerDown_L:.28,mouthLowerDown_R:.28}),card('revolted grimace',{mouthUpperUp_L:.92,mouthUpperUp_R:.82,mouthStretch_L:.62,mouthStretch_R:.62,mouthFrown_L:.54,mouthFrown_R:.54})])}
};
export const EXPRESSION_MORPH_FILES={eyeBlink_L:'eyeBlink_L.obj',eyeBlink_R:'eyeBlink_R.obj',eyeSquint_L:'eyeSquint_L.obj',eyeSquint_R:'eyeSquint_R.obj',eyeWide_L:'eyeWide_L.obj',eyeWide_R:'eyeWide_R.obj',browInnerUp_L:'browInnerUp_L.obj',browInnerUp_R:'browInnerUp_R.obj',browOuterUp_L:'browOuterUp_L.obj',browOuterUp_R:'browOuterUp_R.obj',browDown_L:'browDown_L.obj',browDown_R:'browDown_R.obj',cheekRaiser_L:'cheekRaiser_L.obj',cheekRaiser_R:'cheekRaiser_R.obj',noseSneer_L:'noseSneer_L.obj',noseSneer_R:'noseSneer_R.obj',mouthSmile_L:'mouthSmile_L.obj',mouthSmile_R:'mouthSmile_R.obj',mouthFrown_L:'mouthFrown_L.obj',mouthFrown_R:'mouthFrown_R.obj',mouthShrugLower:'mouthShrugLower.obj'};
export const EXPRESSION_MOUTH_KEYS=new Set(['mouthSmile_L','mouthSmile_R','mouthFrown_L','mouthFrown_R','mouthPress_L','mouthPress_R','mouthDimple_L','mouthDimple_R','mouthRollUpper','mouthRollLower','mouthStretch_L','mouthStretch_R','mouthShrugUpper','mouthShrugLower','mouthUpperUp_L','mouthUpperUp_R','mouthLowerDown_L','mouthLowerDown_R']);
const choose=list=>list[Math.floor(Math.random()*list.length)],clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),smooth=x=>{const v=clamp(x);return v*v*(3-2*v)};
export class ExpressionDeck{
  constructor(){this.family='attentive';this.intensity='subtle';this.mode='wander';this.strength=.85;this.pace=.75;this.weights={};this.labels=[];this.history=new Map();this.started=performance.now()/1000;this.nextBlink=this.started+2.4;this.blinkStarted=-1;this.doubleBlink=-1;this.deal('attentive')}
  deal(name=this.family){this.family=FAMILIES[name]?name:'attentive';const d=FAMILIES[this.family],level=this.intensity==='any'?choose(['subtle','expressive','extreme']):this.intensity,recent=this.history.get(`${this.family}:${level}`)||[];let cards,sig;for(let i=0;i<16;i++){cards=[choose(d.brows[level]),choose(d.eyes[level]),choose(d.mouth[level])];sig=cards.map(c=>c.label).join('|');if(!recent.includes(sig))break}const jitter=.94+Math.random()*.12;this.weights={};cards.forEach(c=>Object.entries(c.weights).forEach(([k,v])=>this.weights[k]=(this.weights[k]||0)+v*jitter));this.labels=[level,...cards.map(c=>c.label)];recent.unshift(sig);this.history.set(`${this.family}:${level}`,recent.slice(0,6));this.started=performance.now()/1000;return this.snapshot()}
  setIntensity(value){if(['subtle','expressive','extreme','any'].includes(value)){this.intensity=value;this.deal()}}
  setMode(mode){if(['hold','breathe','surface','wander'].includes(mode))this.mode=mode;this.started=performance.now()/1000}
  snapshot(){return{family:this.family,intensity:this.intensity,mode:this.mode,labels:[...this.labels],strength:this.strength,pace:this.pace}}
  blink(t){if(this.doubleBlink>0&&t>=this.doubleBlink){this.blinkStarted=t;this.doubleBlink=-1}if(this.blinkStarted<0&&t>=this.nextBlink){this.blinkStarted=t;this.nextBlink=t+2.6+Math.random()*4.8;if(Math.random()<.16)this.doubleBlink=t+.42}if(this.blinkStarted<0)return 0;const age=t-this.blinkStarted;if(age<.09)return smooth(age/.09);if(age<.135)return 1;if(age<.34)return 1-smooth((age-.135)/.205);this.blinkStarted=-1;return 0}
  sample(t=performance.now()/1000){const out={},age=(t-this.started)*this.pace,put=(k,v)=>out[k]=(out[k]||0)+v*this.strength;let envelope=1;if(this.mode==='breathe'){const c=.5-.5*Math.cos(age*Math.PI*2/13.5);envelope=.035+.965*smooth(c)}else if(this.mode==='surface')envelope=age<3.2?smooth(age/3.2):age<5.6?1:age<11.4?1-smooth((age-5.6)/5.8):0;Object.entries(this.weights).forEach(([k,v],i)=>{let e=envelope;if(this.mode==='wander'){const side=k.endsWith('_R')?.43:0,w=Math.pow(Math.max(0,Math.sin(t*this.pace*(.075+(i%5)*.013)+i*1.37+side)),1.7+(i%3)*.3);e=.16+.84*w}put(k,v*e)});const b=this.blink(t);out.eyeBlink_L=b;out.eyeBlink_R=b*.97;if(b>.01){out.eyeWide_L=(out.eyeWide_L||0)*(1-b);out.eyeWide_R=(out.eyeWide_R||0)*(1-b)}return out}
}
