const card=(label,weights={})=>({label,weights});
const FAMILIES={
  attentive:{brows:[card('quiet inner lift',{browInnerUp_L:.18,browInnerUp_R:.18}),card('outer attention',{browOuterUp_L:.17,browOuterUp_R:.17}),card('left brow leads',{browInnerUp_L:.22,browOuterUp_R:.10}),card('brows remain still')],eyes:[card('soft focus',{eyeSquint_L:.09,eyeSquint_R:.09}),card('eyes open slightly',{eyeWide_L:.14,eyeWide_R:.14}),card('one eye considers',{eyeSquint_L:.14,eyeSquint_R:.05}),card('eyes remain clear')],mouth:[card('lips gather',{mouthPress_L:.10,mouthPress_R:.10}),card('almost a smile',{mouthSmile_L:.10,mouthSmile_R:.07}),card('upper lip attends',{mouthShrugUpper:.10}),card('mouth remains neutral')]},
  warm:{brows:[card('open brows',{browOuterUp_L:.13,browOuterUp_R:.13}),card('friendly inner lift',{browInnerUp_L:.12,browInnerUp_R:.12}),card('one brow welcomes',{browOuterUp_L:.16,browInnerUp_R:.07}),card('brows remain soft')],eyes:[card('cheeks rise',{cheekRaiser_L:.18,cheekRaiser_R:.18}),card('smiling squint',{eyeSquint_L:.16,eyeSquint_R:.16}),card('uneven warmth',{cheekRaiser_L:.20,cheekRaiser_R:.11}),card('eyes remain open')],mouth:[card('balanced smile',{mouthSmile_L:.34,mouthSmile_R:.34}),card('crooked smile',{mouthSmile_L:.40,mouthSmile_R:.20}),card('contained dimple',{mouthDimple_L:.30,mouthDimple_R:.22}),card('private smile',{mouthSmile_L:.19,mouthSmile_R:.14,mouthPress_L:.07,mouthPress_R:.07})]},
  sceptical:{brows:[card('left brow challenges',{browDown_L:.34,browInnerUp_R:.24}),card('right brow challenges',{browDown_R:.34,browInnerUp_L:.24}),card('brows narrow',{browDown_L:.23,browDown_R:.23}),card('outer brow question',{browOuterUp_L:.24,browDown_R:.16})],eyes:[card('left eye narrows',{eyeSquint_L:.27,eyeSquint_R:.08}),card('right eye narrows',{eyeSquint_R:.27,eyeSquint_L:.08}),card('measured squint',{eyeSquint_L:.18,eyeSquint_R:.18}),card('small sneer',{noseSneer_L:.16,noseSneer_R:.08})],mouth:[card('one-sided press',{mouthPress_L:.25,mouthPress_R:.10}),card('mouth pulls aside',{mouthStretch_L:.21,mouthStretch_R:.08}),card('doubtful corner',{mouthFrown_R:.20,mouthPress_L:.10}),card('restrained dimple',{mouthDimple_L:.17,mouthPress_R:.14})]},
  concerned:{brows:[card('inner brows rise',{browInnerUp_L:.45,browInnerUp_R:.45}),card('uneven worry',{browInnerUp_L:.48,browInnerUp_R:.30}),card('brow pinch',{browInnerUp_L:.30,browInnerUp_R:.30,browDown_L:.10,browDown_R:.10}),card('one brow searches',{browInnerUp_R:.40,browOuterUp_L:.12})],eyes:[card('eyes search',{eyeWide_L:.19,eyeWide_R:.19}),card('painful squint',{eyeSquint_L:.15,eyeSquint_R:.15}),card('uneven uncertainty',{eyeWide_L:.18,eyeSquint_R:.09}),card('cheeks tense',{cheekRaiser_L:.10,cheekRaiser_R:.10})],mouth:[card('corners fall',{mouthFrown_L:.23,mouthFrown_R:.23}),card('lower lip worries',{mouthShrugLower:.18}),card('one corner falls',{mouthFrown_L:.25,mouthFrown_R:.10}),card('lips part downward',{mouthLowerDown_L:.14,mouthLowerDown_R:.14,mouthPress_L:.06,mouthPress_R:.06})]},
  guarded:{brows:[card('brows settle',{browDown_L:.16,browDown_R:.16}),card('one brow locks',{browDown_L:.20,browDown_R:.10}),card('inner tension',{browInnerUp_L:.10,browInnerUp_R:.10,browDown_L:.11,browDown_R:.11}),card('brows reveal nothing')],eyes:[card('eyes narrow',{eyeSquint_L:.14,eyeSquint_R:.14}),card('side tension',{eyeSquint_L:.18,eyeSquint_R:.08}),card('cheeks brace',{cheekRaiser_L:.09,cheekRaiser_R:.09}),card('eyes remain unreadable')],mouth:[card('lips seal',{mouthPress_L:.27,mouthPress_R:.27}),card('upper lip rolls in',{mouthRollUpper:.22,mouthPress_L:.09,mouthPress_R:.09}),card('lower lip rolls in',{mouthRollLower:.20,mouthPress_L:.11,mouthPress_R:.11}),card('one side locks',{mouthPress_L:.29,mouthPress_R:.13})]},
  activated:{brows:[card('brows spring open',{browInnerUp_L:.38,browInnerUp_R:.38,browOuterUp_L:.28,browOuterUp_R:.28}),card('one brow fires first',{browOuterUp_L:.40,browInnerUp_R:.27}),card('central alarm',{browInnerUp_L:.48,browInnerUp_R:.48}),card('sharp outer lift',{browOuterUp_L:.38,browOuterUp_R:.38})],eyes:[card('eyes widen',{eyeWide_L:.50,eyeWide_R:.50}),card('uneven startle',{eyeWide_L:.55,eyeWide_R:.35}),card('tense activation',{eyeWide_L:.30,eyeWide_R:.30,cheekRaiser_L:.10,cheekRaiser_R:.10}),card('alert squint',{eyeSquint_L:.16,eyeSquint_R:.16,cheekRaiser_L:.12,cheekRaiser_R:.12})],mouth:[card('upper lip lifts',{mouthUpperUp_L:.20,mouthUpperUp_R:.20}),card('mouth stretches',{mouthStretch_L:.25,mouthStretch_R:.25}),card('lower lip drops',{mouthLowerDown_L:.20,mouthLowerDown_R:.20}),card('startled restraint',{mouthShrugUpper:.18,mouthPress_L:.08,mouthPress_R:.08})]}
};

export const EXPRESSION_MORPH_FILES={
  eyeBlink_L:'eyeBlink_L.obj',eyeBlink_R:'eyeBlink_R.obj',eyeSquint_L:'eyeSquint_L.obj',eyeSquint_R:'eyeSquint_R.obj',eyeWide_L:'eyeWide_L.obj',eyeWide_R:'eyeWide_R.obj',
  browInnerUp_L:'browInnerUp_L.obj',browInnerUp_R:'browInnerUp_R.obj',browOuterUp_L:'browOuterUp_L.obj',browOuterUp_R:'browOuterUp_R.obj',browDown_L:'browDown_L.obj',browDown_R:'browDown_R.obj',
  cheekRaiser_L:'cheekRaiser_L.obj',cheekRaiser_R:'cheekRaiser_R.obj',noseSneer_L:'noseSneer_L.obj',noseSneer_R:'noseSneer_R.obj',mouthSmile_L:'mouthSmile_L.obj',mouthSmile_R:'mouthSmile_R.obj',mouthFrown_L:'mouthFrown_L.obj',mouthFrown_R:'mouthFrown_R.obj',mouthShrugLower:'mouthShrugLower.obj'
};
export const EXPRESSION_MOUTH_KEYS=new Set(['mouthSmile_L','mouthSmile_R','mouthFrown_L','mouthFrown_R','mouthPress_L','mouthPress_R','mouthDimple_L','mouthDimple_R','mouthRollUpper','mouthRollLower','mouthStretch_L','mouthStretch_R','mouthShrugUpper','mouthShrugLower','mouthUpperUp_L','mouthUpperUp_R','mouthLowerDown_L','mouthLowerDown_R']);

const choose=list=>list[Math.floor(Math.random()*list.length)];
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const smooth=x=>{const v=clamp(x);return v*v*(3-2*v)};
export class ExpressionDeck{
  constructor(){this.family='attentive';this.mode='wander';this.strength=.7;this.pace=.75;this.weights={};this.labels=[];this.history=new Map();this.started=performance.now()/1000;this.nextBlink=this.started+2.4;this.blinkStarted=-1;this.doubleBlink=-1;this.deal('attentive')}
  deal(name=this.family){this.family=FAMILIES[name]?name:'attentive';const d=FAMILIES[this.family],recent=this.history.get(this.family)||[];let cards,sig;for(let i=0;i<16;i++){cards=[choose(d.brows),choose(d.eyes),choose(d.mouth)];sig=cards.map(c=>c.label).join('|');if(!recent.includes(sig))break}const jitter=.88+Math.random()*.24;this.weights={};cards.forEach(c=>Object.entries(c.weights).forEach(([k,v])=>this.weights[k]=(this.weights[k]||0)+v*jitter));this.labels=cards.map(c=>c.label);recent.unshift(sig);this.history.set(this.family,recent.slice(0,6));this.started=performance.now()/1000;return this.snapshot()}
  setMode(mode){if(['hold','breathe','surface','wander'].includes(mode))this.mode=mode;this.started=performance.now()/1000}
  snapshot(){return{family:this.family,mode:this.mode,labels:[...this.labels],strength:this.strength,pace:this.pace}}
  blink(t){if(this.doubleBlink>0&&t>=this.doubleBlink){this.blinkStarted=t;this.doubleBlink=-1}if(this.blinkStarted<0&&t>=this.nextBlink){this.blinkStarted=t;this.nextBlink=t+2.6+Math.random()*4.8;if(Math.random()<.16)this.doubleBlink=t+.42}if(this.blinkStarted<0)return 0;const age=t-this.blinkStarted;if(age<.09)return smooth(age/.09);if(age<.135)return 1;if(age<.34)return 1-smooth((age-.135)/.205);this.blinkStarted=-1;return 0}
  sample(t=performance.now()/1000){const out={},age=(t-this.started)*this.pace,put=(k,v)=>out[k]=(out[k]||0)+v*this.strength;let envelope=1;if(this.mode==='breathe'){const c=.5-.5*Math.cos(age*Math.PI*2/13.5);envelope=.035+.965*smooth(c)}else if(this.mode==='surface')envelope=age<3.2?smooth(age/3.2):age<5.6?1:age<11.4?1-smooth((age-5.6)/5.8):0;Object.entries(this.weights).forEach(([k,v],i)=>{let e=envelope;if(this.mode==='wander'){const side=k.endsWith('_R') ? .43 : 0,w=Math.pow(Math.max(0,Math.sin(t*this.pace*(.075+(i%5)*.013)+i*1.37+side)),1.7+(i%3)*.3);e=.16+.84*w}put(k,v*e)});const b=this.blink(t);out.eyeBlink_L=b;out.eyeBlink_R=b*.97;if(b>.01){out.eyeWide_L=(out.eyeWide_L||0)*(1-b);out.eyeWide_R=(out.eyeWide_R||0)*(1-b)}return out}
}
